### ISSUE TITLE
passport-saml integration with onelogin 

### ISSUE THREAD

**Issue by SachAtTiwari** [bergie/passport-saml#108]
Hi
Passport-saml is not redirecting to callback url

module.exports = {
        development : {
                app : {
                        name : 'Passport SAML strategy example',
                        port : process.env.PORT || 8080
                },
                passport: {
                        strategy : 'saml',
                        saml : {
                                entryPoint : 'https://app.onelogin.com/trust/saml2/http-post/sso/1234',
                                //issuer : 'https://app.onelogin.com/saml/metadata/1234',
                                issuer: 'http://54.204.231.239:8080/login/callback',
                                callbackUrl : 'http://54.204.231.239:8080/login/callback',
                                cert: "onelogin.pem",
                                identifierFormat: null,
                                additionalParams:{'RelayState':null}
                        }
                }
        }
}
Please help...

**Comment by ploer** [comment]
Not a lot of information here, but keep in mind that it's your SAML provider that redirects back to the callback url.  Presumably something about the configuration you are passing to onelogin is not being accepted.

**Comment by luozhaoyu** [comment]
I have the same issue which does not redirect back to callbackUrl...
