### ISSUE TITLE
Response rejected if both the Response and the contained Assertion are signed

### ISSUE THREAD

**Issue by nonspecialist** [bergie/passport-saml#112]
If I have a SAML Response that's signed, with an Assertion inside that response that is also signed, like:

```xml
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:xs="http://www.w3.org/2001/XMLSchema" Destination="SOMEWHERE" ID="_518a6e4ed1b5eba98a3c6a6459b6cd95" InResponseTo="_cc57970f624daa0e1b6148f0a39033602e5e80c732" IssueInstant="2015-09-23T23:50:41.052Z" Version="2.0">
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:Reference URI="#_518a6e4ed1b5eba98a3c6a6459b6cd95">
    ...
    VALID_SIGNATURE_HERE_FOR_518a6e4ed1b5eba98a3c6a6459b6cd95
  </ds:Signature>
...
  <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_aa5ad5b81e72e69a5c048884a500f8ce" IssueInstant="2015-09-23T23:50:41.052Z" Version="2.0">
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:Reference URI="#_aa5ad5b81e72e69a5c048884a500f8ce">
      ...
      VALID_SIGNATURE_HERE_FOR_aa5ad5b81e72e69a5c048884a500f8ce
  </saml2:Assertion>
</saml2p:Response>
```

Then, in `SAML.prototype.validateSignature()`:

```javascript
  var xpathSigQuery = ".//*[local-name(.)='Signature' and " +
                      "namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']";
  var signatures = xpath(currentNode, xpathSigQuery);
  // This function is expecting to validate exactly one signature, so if we find more or fewer
  //   than that, reject.
  if (signatures.length != 1) {
   return false;
  }
````

matches _both_ signatures, because the XPATH query is just matching on all signatures anywhere in the response.

Would it be better, instead, to have the function validate that each ID is signed exactly once?

**Comment by ploer** [comment]
Is this something you're seeing in the wild?

I'd have to think carefully about the implications are here -- correctness in XML signature verification is tricky.  But its probably true that the current check is overly conservative.  

This function is basically trying to validate the signature at the level of the current node, so I'm thinking that the shape of the right change would be to just make sure that we find exactly one signature that is valid for the top level node.  We can probably ignore the signatures that match sub-nodes.

**Comment by ploer** [comment]
If that sounds about right to you, if you can put together a PR I'd be happy to take a look.  Thanks!
