### ISSUE TITLE
Reference validation error

### ISSUE THREAD

**Issue by idan08** [bergie/passport-saml#125]
I'm trying to create a service provider for authentication. My app is crashing in the validate reference step - I get the response from the server (adfs 2.0) that includes my right claim so the server does authenticates me correctly, but in the reference validation I have a problem that the digest value in the reference isn't like the value that the passport-saml calculates by hashing the assertion. I checked and they both using the same algorithm. Any thoughts?

**Comment by idan08** [comment]
I have &quot; in the assertion that being hashed instead of "
Do you think that's might be the problem? Beside that nothing seems weird in the assertion.

**Comment by idan08** [comment]
I didn't find an edit option so exuse me for all the comments, but after I had send the last comment I saw that it changes&quot; to ", my question is that I see in debug that the cannon xml contains the first option and not ", can that be the problem with the hashing?

**Comment by idan08** [comment]
Damm it, the other option of " that I mean to is &quot

**Comment by ploer** [comment]
Well, if you somehow got an extra level of encoding in there, that would definitely break the signature.  

If that doesn't turn out to be the issue you might just want to try running the digest separately in a different tool or a test harness to see if it seems to check out.

Good luck. :-)
