### ISSUE TITLE
Question: how to access attributes of SAML assertion?

### ISSUE THREAD

**Issue by rolodato** [bergie/passport-saml#126]
I noticed that `req.body.SAMLResponse` has the full SAML response from the IDP. Is this response parsed somewhere or should I parse the response myself to access all the attributes in it? Thanks!

**Comment by gnawhleinad** [comment]
The attributes are parsed in [`lib/passport-saml/saml.js#L553`](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L553).

**Comment by rolodato** [comment]
Not sure I follow. Is there any way to access parsed attributes directly or does the response have to be parsed manually?

**Comment by gnawhleinad** [comment]
Attributes are parsed into the profile object at [`lib/passport-saml/saml.js#L677`](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L677).

**Comment by rolodato** [comment]
Sorry, I wasn't seeing them because I was stripping them elsewhere. Thanks!
