### ISSUE TITLE
Redirects in infinite loop if a body parser is not set up for express

### ISSUE THREAD

**Issue by jrop** [bergie/passport-saml#128]
Minor, but should be documented: when defining the callback route:

```
let app = express()
app.get('/login', passport.authenticate('saml', { failureRedirect: '/' }), (req, res) => res.redirect('/'))
app.post('/callback', passport.authenticate('saml', { failureRedirect: '/' }), (req, res) => res.redirect('/'))
```

There needs to be middleware that supports body parsing, otherwise (in my case) it starts redirecting between my IdP and my app indefinitely.

**Comment by ploer** [comment]
Can you submit a PR with the proposed documentation change?  Thanks!

**Comment by joelwass** [comment]
I seem to be having this issue, but i'm using the node package body-parser, what body parser did you end up using to resolve this issue?

**Comment by casey-billett** [comment]
I feel like adding the body-parser middleware has caused functionality in Rocky to break.  When trying to reverse-proxy connections after ensuring authentication, the middleware fails with:

**Comment by PhilippSpo** [comment]
I also had the same issue. Adding the `bodyParser` finally resolved it. 😅

```js
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({ extended: false }));
```

**Comment by mrchief** [comment]
Wasted days chasing this infinite loop issue. Many thanks to OP for creating this issue. There is no mention of it in documentation. :disappointed:

**Comment by jrop** [comment]
@mrchief I created a PR for this a long time ago, but it's had very little activity :( #151

**Comment by salazr** [comment]
Spent a couple hours this morning setting this up on a new app, and encountered the same problem.  It would be nice to have this in the documentation.

**Comment by mrchief** [comment]
Its kinda in the documentation, in its own convoluted way: :wink: 

![image](https://user-images.githubusercontent.com/781818/29191638-6d0bb33a-7dec-11e7-8d69-4da08897723e.png)

**Comment by MardariG** [comment]
This is closed, but I have spend too much time to find out the problem is in body-parser.
This should be as mandatory requirement on the mine README in **bold**. I don't get it why is so hard to mention this. Thanks for awesome library anyway.

**Comment by DORRITO** [comment]
Hello!  If anyone is using express 5, since body parser isn't needed, simply make sure the `app.use(express.urlencoded({ extended: false }));` **_before_** the route calls.

Many thanks to kashiif and makstos above for leading me down that path.  Immense Thanks!

**Comment by markstos** [comment]
@DORRITO Please submit a doc-patch for the Express 5 example syntax.

**Comment by duxing** [comment]
another victim who wastes days here. Thanks for sharing this and saving my life @jrop

**Comment by limwtn** [comment]
I was using "@node-saml/passport-saml": "^5.1.0", "body-parser": "^2.2.0", "express": "^5.1.0", and this combination is going into looping. Only if i used body-parser 1.20.3, then it is working. In the future, i wonder how am i going to update body-parser

**Comment by kashiif** [comment]
@limwtn I have not tried this but @Lrigh1's [comment above](https://github.com/node-saml/passport-saml/issues/128#issuecomment-585620649) mentions that for express 5 you don't need body parser.

> Hello! If anyone is using express 5, since body parser isn't needed, simply make sure the app.use(express.urlencoded({ extended: false })); is before the route calls.
