### ISSUE TITLE
Get "Error: request size did not match content length" when I upload my code to server.  Localhost works perfectly.

### ISSUE THREAD

**Issue by rftse** [bergie/passport-saml#132]
I used the following example to do okta integration
https://github.com/ThoughtWorksInc/okta-samples/tree/master/okta-node-express

The only difference is that I have maxAge for session cookie.  For testing purposes, I have set this to 1000.

The code works perfectly but once is a while (1/10 times) it results in the following error:
*Error: request size did not match content length
   at IncomingMessage.onEnd (/home/me/node_temp_test/node_modules/body-parser/node_modules/raw-body/index.js:298:12)
   at IncomingMessage.emit (events.js:64:17)
   at HTTPParser.onMessageComplete (http.js:137:23)
   at Socket.ondata (http.js:1374:22)
   at TCP.onread (net.js:348:27)*

I see that the okta response to my post url is correct and complete but when I print out what is read in index.js it is missing the first few lines.

**Comment by ploer** [comment]
Sorry, I don't see anything in the above that points to a passport-saml issue.  I'd recommend tracing back which layer of the code those lines are getting cut out at.  Happy to help if you can supply something more specific.

**Comment by rftse** [comment]
I think the issue was caused by node version (v0.6.6) installed on the server.  It was sometimes dropping the first chunk of data from the response.  The node version that I have installed on my local machine is v0.12.2 didn't run into the issue.  I have updated the node version on the server to the latest and seems like the issue has been resolved.

**Comment by ploer** [comment]
Great to hear.  Yeah, 0.6 is probably going to be problematic with a lot of libraries at this point.  I'm currently only testing passport-saml back as far as 0.10, for instance.
