### ISSUE TITLE
Remove Signature element from the xml before verifying it

### ISSUE THREAD

**Issue by zccaliDev** [bergie/passport-saml#149]
in the saml.js file you can see this code
```
sig.loadSignature(signature.toString());
return sig.checkSignature(xml);
```
if the signature element was not removed from the assertion the digest value will be different.
so the correct code will be
```
sig.loadSignature(signature.toString());
//remove the signature tag
doc.removeChild(signature);
return sig.checkSignature(doc.toString());
```

**Comment by markstos** [comment]
@zccaliDev Is change in reference to this part of the [XML Signature Spec?](https://www.w3.org/TR/xmldsig-core/) in section 6.6.3 XPath Filtering:

> Each signature must omit itself from its own digest calculations, but it is also necessary to exclude the second signature element from the digest calculations of the first signature so that adding the second signature does not break the first signature.

**Comment by markstos** [comment]
Could you provide a patch for this which passes the test suite? I tried adding a patch like this to the current code and running the tests and there were a lot of failures.

**Comment by zccaliDev** [comment]
I was using this https://github.com/lmarkus/passport-saml-encrypted forked version from your repo, and it passed 100%, I thing you have some different in here.
