### ISSUE TITLE
Google SAML

### ISSUE THREAD

**Issue by Crispy1975** [bergie/passport-saml#167]
Does passport-saml support Google SAML?

**Comment by springuper** [comment]
+1

**Comment by abelosorio** [comment]
Yes. It does.

```
passport.use(new SamlStrategy(
  {
    path: process.env.REACT_APP_SAML_PATH,
    entryPoint: process.env.REACT_APP_SAML_ENTRYPOINT,
    issuer: process.env.REACT_APP_SAML_ISSUER,
    cert: process.env.REACT_APP_SAML_CERT,
    identifierFormat: 'urn:oasis:names:tc:SAML:2.0:nameid-format:email',
    protocol: 'https://'
  },
  function(profile, done) {
    return done(null, {
      id: profile.uid,
      email: profile.email,
      displayName: profile.cn,
      firstName: profile.givenName,
      lastName: profile.sn
    });
  })
);
```

And (in app.js):

```
// @see https://github.com/bergie/passport-saml#provide-the-authentication-callback
app.get('/auth/sso-login', passport.authenticate(
  process.env.REACT_APP_PASSPORT_STRATEGY,
  {
    successRedirect: '/',
    failureRedirect: '/auth/login',
    failureFlash: true
  }
));

app.post(
  process.env.REACT_APP_SAML_PATH,
  passport.authenticate(
    process.env.REACT_APP_PASSPORT_STRATEGY,
    {
      failureRedirect: '/',
      failureFlash: true
    }
  ),
  (req, res) => {
    res.redirect('/');
  }
);
```

I've used `passport`, `passport-saml`, `express-session`, `cookie-parser` and `body-parser`.

Let me know if you need a hand.

**Comment by aby040** [comment]
@abelosorio Have you tried fetching user groups as part of the SAML response from google? I was able to add custom field to users which can be added in 'Attribute Mapping' section, but I could not find a way to fetch the groups the user belongs to (member-of)!

**Comment by abelosorio** [comment]
Hi @aby040!

No, I haven't done that. Sadly I'm not longer part of the project where I used Google SAML.

Sorry man, I cannot help this time :(

**Comment by ChakrapaniKulkarni** [comment]
How to extract the user profile from the samlstrategy callback.. we want to show the logged in user's name, email,..etc.. Any idea?

**Comment by cjbarth** [comment]
Do you know which fork? It would be nice to have that fork contribute back to this project if at all possible.

**Comment by rayfoss** [comment]
@cjbarth it's old https://github.com/DmtrPn/passport-saml 

He took a Tailor made brute force approach to the problem... It would be more helpful to have a more general solution that might be useful even outside of Google... Like Instagram login, Twitter or other edge cases, perhaps automated testing or staging and contractor accounts.
