### ISSUE TITLE
passport.authenticate('saml') - TypeError: Cannot read property 'stripPrefix' of undefined

### ISSUE THREAD

**Issue by johnmellis** [bergie/passport-saml#172]
I'm using OneLogin as an IdP and am able to successfully authenticate through their SAML connector, however when `passport.authenticate('saml',{failureRedirect:'/home',failureFlash:true})`  is added to the callback function inside of my application I receive the following error:

`TypeError: Cannot read property 'stripPrefix' of undefined
   at SAML.processValidlySignedAssertion (/Users/johnellis/supdash/node_modules/passport-saml/lib/passport-saml/saml.js:653:42)...
`

If I remove the authenticate section of the callback, I receive a valid session ID in response from OneLogin.

Any help would be appreciated.

**Comment by johnmellis** [comment]
This was resolved by installing xml2js separately (I think the version included in this package is out of date).

**Comment by pdspicer** [comment]
Couldn't tell you why this would happen, only that neither this project nor xml2js was updated in any significant way around that time, and based on the fact that no one else has reported having this problem (nor can I reproduce it) I'd say your best bet would be to try clearing your npm cache, uninstalling, and then reinstalling your project dependencies. Probably just an anomaly.
