### ISSUE TITLE
PEM_read_bio_PUBKEY Error When Parsing OneLogin Response

### ISSUE THREAD

**Issue by maestroh** [bergie/passport-saml#174]
I keep getting the `PEM_read_bio_PUBKEY failed` error when xml2js parses the saml response. I've tried updating to the latest xml2js (v0.4.17) to see if that would fix it, but I've had no luck. It seems to fail on the saxparser.write function.

I've manually looked through the response and it looks ok. Any ideas on how to resolve this issue? Has anyone had any success lately with using passport-saml and OneLogin?

**Comment by louis-sanna** [comment]
@maestroh I have the same problem. Any progress on this issue?

**Comment by pdspicer** [comment]
Can you provide a stack trace & sample response along with the configuration you are using for passport-saml? Based on the error message you're reporting I suspect this is more likely an issue in signature checking or decryption, as that error is usually one you'll see from the `crypto` module.

**Comment by louis-sanna** [comment]
@pdspicer in my case the problem was unrelated to crypto module.

**Comment by pdspicer** [comment]
Do you have any more information that could be of use?

**Comment by madhu-guruprasad** [comment]
@louis-sanna can you provide more information about what the issue was and how you fixed it? We're facing the same issue.

**Comment by markstos** [comment]
This appears to be an external issue. I have used this project with OneLogin myself, so general compatibility with that provider is not the issue.
