### ISSUE TITLE
Does this lib work client side only?

### ISSUE THREAD

**Issue by Gobliins** [bergie/passport-saml#175]
Well title says it. 
I want to do a SAML login to my idp (azure ad), but it should work from client side javascript (no node etc.) only.

**Comment by pdspicer** [comment]
Don't know that anyone has bothered testing but this lib almost certainly doesn't work client side, as it has dependencies on node-specific modules like http (even if just indirectly through passport). Not to mention I don't think SAML really works client-side only either. The whole use case is to authenticate a user to a service provider through assertions made by an identity provider, in your case you are missing a service provider.
