### ISSUE TITLE
Logout Functionality

### ISSUE THREAD

**Issue by Abhimanyu310** [bergie/passport-saml#176]
Hello, could someone provide an example of how exactly the logout needs to be implemented? 

In my efforts, I tried answers for these two issues:
[62](https://github.com/bergie/passport-saml/issues/62)
[93](https://github.com/bergie/passport-saml/issues/93)

But, it seems that another attribute needs to be passed with the sessionIndex. I get the following error when trying to logout from the IDP. 

`Missing attribute value for attribute Format of element saml:NameID`

I couldn't find any where how and where to pass this ?

**Comment by casey-billett** [comment]
I got around this by simply ensuring that it has it _is_ defined:
```
  var strategy = new SamlStrategy(
    {
      path: config.passport.saml.path,
      entryPoint: config.passport.saml.entryPoint,
      issuer: config.passport.saml.issuer,
      cert: config.passport.saml.cert,
      logoutUrl: config.passport.saml.logoutUrl,
      logoutCallback: config.passport.saml.logoutCallback,
      acceptedClockSkewMs: config.passport.saml.acceptedClockSkewMs
    },
    function (profile, done) {
      log.info(profile);
      return done(null,
        {
          id: profile.CustID,
          email: profile.Email,
          displayName: `${profile.FirstName} ${profile.LastName}`,
          firstName: profile.FirstName,
          lastName: profile.LastName,
          nameID: profile.nameID,
          nameIDFormat: profile.nameIDFormat
        });
    });

  log.info(strategy.generateServiceProviderMetadata());
  passport.use(strategy);
```
Voila!

**Comment by casey-billett** [comment]
Also,
```
app.get('/logout', function(req, res) {
    if (!req.user) res.redirect('/');
    log.info("initiating logout", req.log, req.user);
    return passport._strategy('saml').logout(req, function(err, uri) {
      return res.redirect(uri);
    });
});
```
```
app.get(config.passport.saml.logoutCallback, function(req, res) {
    req.log.info("completing logout", req.user);
    req.logout();
    res.redirect('/');
});
```
Where config.passport.saml.logoutCallback is simply '/logout/callback'.

**Comment by Abhimanyu310** [comment]
@casey-billett Yes, thank you, and I had it figured out. I was not storing the nameID field in the session and hence it wasn't available during logout.

**Comment by oversio** [comment]
Hi guys! could you tell me what is the value for ``` req.user ``` ? please! I'm getting this error in the browser...

```
400. That’s an error.

Error parsing the request, malformed_request: The SAML request is malformed. That’s all we know.
```

**Comment by ehabAbdelMawla** [comment]
i have same issue with this error message from Microsoft
AADSTS7500525: There was an XML error in the SAML message at line 1, position 445. Verify that the XML content of the SAML messages conforms to the SAML protocol specifications.

any updates !

**Comment by ehabAbdelMawla** [comment]
@oversio  any update
