### ISSUE TITLE
The certificate of the IdP MUST be required

### ISSUE THREAD

**Issue by pitbulk** [bergie/passport-saml#180]
Right now if a dev is not providing the IdP's x509cert the signature validation is not processed.
This is sooo risky.

Instead of avoid the signature validation process, if a valid IdP's x509cert is not provided, I recommend to throw an exception.

**Comment by andrsnn** [comment]
:+1 I absolutely agree with this.  Is there at all a reason why this check does not currently occur? Any falsy value currently will bypass signature validation.  It seems very likely that a user may accidentally provide an empty string thereby exposing a security risk.  I would at least assume if the cert property is not undefined e.g. `{ cert: value }` that it should be checked.

**Comment by pdspicer** [comment]
Signatures are optional, and may not be provided by some IDPs (see [saml-core-2.0-os](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) section 5.1). That being said, if a signature is present, then the same-core-2.0-os spec requires that it be validated. So the check for a supplied cert should only occur at whatever point a signature element is actually found.

**Comment by pitbulk** [comment]
> Signatures are optional, and may not be provided by some IDPs
Are you serious @pdspicer?

A Signature on a SAMLResponse (Assertion or the full Message element signed) is a MUST on the SAML standard in order to verify the integrity of the data. Without signature, anyone can impersonate the SAMLResponse...

Section 5.1 and 5.2 only indicates that Message and Assertion element MAY be signed, to indicate that is not a requirement to sign both...(concept explained on 5.3).


P.S I'm worried about your comment [here](https://github.com/bergie/passport-saml/issues/162#issuecomment-290000771). Have you worked with many SAML implementations where SAMLResponses with no signature element were valid?

**Comment by pdspicer** [comment]
@pitbulk appreciate the feedback, reading through the spec on SAML profiles does indicate that signatures are required on SAML responses sent via the HTTP-POST binding (which is the only one fully supported by this project currently). I will stand by my statement that the specification does mark it as optional in general, but amend my comment on the necessity of the field in that I agree, for the supported bindings, signatures must be present and validation must be performed. 
My intent is merely to ensure that the implementation here is not constrained beyond what is stated in the specification. I welcome feedback and the opportunity to be corrected when others have different experiences and understanding from my own. Hopefully you will take this into consideration and continue to provide positive feedback to this project.

**Comment by pitbulk** [comment]
@pdspicer I implemeted SAML toolkits for [PHP](https://github.com/onelogin/php-saml), [Python](https://github.com/onelogin/python-saml), [Java](https://github.com/onelogin/java-saml) and [Ruby](https://github.com/onelogin/ruby-saml). But unfortunately Node.js is a language out of my control.

As I mentioned in the ["looking for maintainer"](https://github.com/bergie/passport-saml/issues/162#issuecomment-275846995) thread, I will try to push that project, so let me know if you have doubts about the SAML protocol and use Onelogin's open source SAML toolkits, or others open source SAML toolkits as inspiration.

**Comment by pdspicer** [comment]
@pitbulk yes I noticed you had done one or two things with SAML before ;) I will be sure to get in touch, I think it would be valuable to collaborate wherever possible.

**Comment by alexstuart** [comment]
I agree that signature checking should be mandatory.

@pdspicer wrote:
> My intent is merely to ensure that the implementation here is not constrained beyond what is stated in the specification.

Having an insecure default (that is to say, if you don't configure the IdP's public certificate then the module won't check signatures) is the wrong way to develop authentication software. Better to have a secure default which requires a certificate to be configured. If you want to be flexible, then you can provide an override to not check signatures. And put a big warning next to the override.

> the check for a supplied cert should only occur at whatever point a signature element is actually found.

No, because if an assertion does not have a signature, then it is presumed valid. This means an attacker can fake an assertion and not have to sign it, lowering the cost of an attack. Signature checking (and rejection if there is no signature element) should be mandatory unless the deployer overrides the secure default.

I think that checking whether there is a certificate should be added to the initialize function, and fail fast.

**Comment by pdspicer** [comment]
@alexstuart apologies if you misinterpreted my last comment, I think we are all on the same page here. Certificate must be required and validation for assertions must fail if signature is missing.
