### ISSUE TITLE
SAML Signature validation fails

### ISSUE THREAD

**Issue by Honold** [bergie/passport-saml#190]
Hello,

we use an ADFS resource partner deployment. [Configuring Partner Organizations.](https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/deployment/configuring-partner-organizations) Signature validation fails in passport-saml v0.12 though the signature is valid when I check on https://www.samltool.com/validate_response.php.

SAML Response looks like this:

<samlp:Response ID="_d116c8e3-c09a-46fd-b710-d4937edab0dc"
                Version="2.0"
                IssueInstant="2017-02-24T11:39:39.049Z"
                Destination="https://xo.mydomain.com/signin/saml/callback"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                InResponseTo="_cc027d8d07855854b400"
                xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://identity.mydomain.com/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion ID="_ae87ab4f-434e-4a9a-893e-ecba64686ef4"
               IssueInstant="2017-02-24T11:39:39.049Z"
               Version="2.0"
               xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
               >
        <Issuer>https://identity.mydomain.com/adfs/services/trust</Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                <ds:Reference URI="#_ae87ab4f-434e-4a9a-893e-ecba64686ef4">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    <ds:DigestValue>somedigest</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>signature</ds:SignatureValue>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>certificate</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">firstname.lastname@otherdomain.net</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="_cc027d8d07855854b400"
                                         NotOnOrAfter="2017-02-24T11:44:39.049Z"
                                         Recipient="https://xo.mydomain.com/signin/saml/callback"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2017-02-24T11:39:39.037Z"
                    NotOnOrAfter="2017-02-24T12:39:39.037Z"
                    >
            <AudienceRestriction>
                <Audience>https://xo.mydomain.com</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="uid"
                       a:OriginalIssuer="http://fs.otherdomain.net/adfs/services/trust"
                       xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"
                       >
                <AttributeValue>firstname.lastname@otherdomain.net</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2017-02-24T11:39:38.425Z"
                        SessionIndex="_ae87ab4f-434e-4a9a-893e-ecba64686ef4"
                        >
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>

How can I fix this issue?

Best Regards
Matt

**Comment by Honold** [comment]
[saml_response.txt](https://github.com/bergie/passport-saml/files/799392/saml_response.txt)

**Comment by pdspicer** [comment]
Without seeing how you're configuring it I can't say for sure but it might be an issue with the format of the certificate you're providing, can you confirm that you are using a PEM-encoded `cert` formatted with no -----BEGIN/END CERTIFICATE----- lines or newlines? Currently this is the preferred format (it's shown in the README for an example of what I'm talking about).

**Comment by markstos** [comment]
No further response fro the OP, so closing.
