### ISSUE TITLE
Option "authnContext" does not respect SAML2 protocol schema compliancy 

### ISSUE THREAD

**Issue by PaoloBertuzzo** [bergie/passport-saml#194]
self.options.authnContext is not compliant with SAML protocol schema (https://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd). where 

<complexType name="RequestedAuthnContextType"><choice><element ref="saml:AuthnContextClassRef" maxOccurs="unbounded"/><element ref="saml:AuthnContextDeclRef" maxOccurs="unbounded"/></choice><attribute name="Comparison" type="samlp:AuthnContextComparisonType" use="optional"/></complexType>

AuthnContextClassRef is unbounded. Allow for simple string or array specification for multiple envelopes.

**Comment by pdspicer** [comment]
Closing as duplicate of #181
