### ISSUE TITLE
Passport-saml implementation with Okta

### ISSUE THREAD

**Issue by macray125** [bergie/passport-saml#198]
Hi Ma'am/Sir

Can you help me on how to implement okta and passport-saml?

**Comment by jherault** [comment]
Create an account on okta preview (for testing okta)
Take a look at: https://gist.github.com/jherault/50e511a682463a4c1cf73a52ed24f7ab
You can't test on local, you should deploy this app (use Heroku as I do for example)
Best,

**Comment by madtaras** [comment]
@jherault what's the problem with testing locally?
Will ngrok help testing locally?
