### ISSUE TITLE
Add support for Signed AuthnRequests using the HTTP-POST Binding.

### ISSUE THREAD

**Issue by richardTowers** [bergie/passport-saml#206]
Hello, I'm a developer for the UK's Government Digital Service. I work on the [GOV.UK Verify](https://govuk-verify.cloudapps.digital/) product, which is a reasonably complex SAML federation.

GOV.UK Verify uses the SAML HTTP-POST binding, and mandates that AuthnRequests are signed.

At the moment it looks like passport-saml does not sign HTTP-POST AuthnRequests. The signing process is a little different from the HTTP-Redirect binding (the signature lives in the XML, rather than the URL), but it's supported by XML Crypto, so it shouldn't be too difficult to add.

If this feature is something you'd accept a Pull Request for we'd be very keen to contribute. I've made a start in [my fork](https://github.com/richardTowers/passport-saml).

Most of all: thanks to all the contributors of passport-saml so far - having good open source implementations of infrastructure like this is fantastic 💯 .

**Comment by richardTowers** [comment]
Raised PR #207 to address signing of HTTP-POST AuthnRequests. Let me know if it needs any more work.

**Comment by ajshetye** [comment]
HI,
I work for a tech company in US. We are trying to use this feature for request signing. Any news for why it did not make the merge. 

Thanks,
Anuj

**Comment by markstos** [comment]
@ajshetye Since you also interested in this feature getting merged, please peer-review #207 and provide feedback there about recommended changes or a recommendation to merge it.

**Comment by joedjc** [comment]
@richardTowers @markstos  We've come across this issue recently - has there been a consensus on the best approach?

**Comment by crutley** [comment]
Updating here to say that PR #207 was just rebased against master by @richardTowers, had a change to improve spec compliance, and was successfully tested against my company's PingFederate server.

**Comment by markstos** [comment]
I believe this is addressed by #207, so closing.

**Comment by markstos** [comment]
A new release of passport-saml today includes this change.
