### ISSUE TITLE
Unable to locate metadata for 'passport-saml'

### ISSUE THREAD

**Issue by bosslee** [bergie/passport-saml#211]
Hi all 

I like to ask if anyone is getting an error with openidp.feide.no?

I followed the example app by Gerard
Set up the app have it running 
but when I click login, I ran into the following

```
SimpleSAML_Error_MetadataNotFound: METADATANOTFOUND('%ENTITYID%' => '\'passport-saml\'')
Backtrace:
3 /www/openidp.feide.no/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:293 (SimpleSAML_Metadata_MetaDataStorageHandler::getMetaData)
2 /www/openidp.feide.no/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:310 (SimpleSAML_Metadata_MetaDataStorageHandler::getMetaDataConfig)
1 /www/openidp.feide.no/simplesamlphp/modules/saml/lib/IdP/SAML2.php:296 (sspmod_saml_IdP_SAML2::receiveAuthnRequest)
0 /www/openidp.feide.no/simplesamlphp/www/saml2/idp/SSOService.php:19 (N/A)
```

So like to ask if I'm missing out anything here? or could someone give me a hint to get the example app working?

or is there any other testing site that I can leverage on?

Thank you very much 

I have registered for an account openidp.feide.no, but I do not see anywhere to upload metadata?

**Comment by ugolas** [comment]
Ran into the same issue while trying the sample to work.
Also I cant seem to "register the site as a service provider".

Did you get the sample / any other way for testing to work?

**Comment by kajiru** [comment]
Having the same problem. Did you resolve this @bosslee ?

**Comment by thomashzhang** [comment]
Bump. I'm having this issue as well. Some help is appreciated.

**Comment by kajiru** [comment]
@thomashzhang Apparently, their service is not open to the general public. You have to be building for the Norwegian edu sector.
