### ISSUE TITLE
Invalid signature, digest doesn't match

### ISSUE THREAD

**Issue by mikevbaker** [bergie/passport-saml#212]
I have this setup in config:
```
passport: {
     strategy: 'saml',
     saml: {
        path: process.env.SAML_PATH || '/sso/acs',
        entryPoint: process.env.SAML_ENTRY_POINT || 'https://idp-domain.com/folder/saml20/login',
         issuer: 'passport-saml',
        cert: process.env.SAML_CERT || 'MIIGm .... iBJdLEPo+OdIW'
     }
}
```

which is used in this strategy:
```
const SamlStrategy = require('passport-saml').Strategy;
var samlStrategy = new SamlStrategy(
    {
        path: config.passport.saml.path,
        entryPoint: config.passport.saml.entryPoint,
        issuer: config.passport.saml.issuer,
        decryptionPvk: pvk,
        cert: config.passport.saml.cert,
        acceptedClockSkewMs: 60000
    },
    function (profile, done) {
        return done(null,
        {
            id: profile.uid,
            email: profile.email,
            displayName: profile.cn,
            firstName: profile.givenName
            lastName: profile.sn
        });
    });

```
This is an excerpt from a samlp:Response that is sent from the IdP to my /sso/acs post handler.

```
<ds:SignedInfo>
  <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
  <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#Assertion-uuidf5cec21-015c-1744-8ab6-e42f35dbee20">
    <ds:Transforms>
      <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
        <xc14n:InclusiveNamespaces xmlns:xc14n="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs saml xsi"/>
      </ds:Transform>
    </ds:Transforms>
    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <ds:DigestValue>DZSPFDmb1ag4wvxjOKdcpFxGa2c=</ds:DigestValue>
  </ds:Reference>
</ds:SignedInfo>

```
I traced the operation down into xml-crypto and I found it stuffing this into the validationErrors.
`invalid signature: for uri #Assertion-uuidf5cec21-015c-1744-8ab6-e42f35dbee20 calculated digest is 0xcAC4ltyxSDCKKE+miR6uge/gs= but the xml to validate supplies digest DZSPFDmb1ag4wvxjOKdcpFxGa2c=`

I also found that the hash algorithm name that was selected was `http://www.w3.org/2000/09/xmldsig#sha1`

Can someone see what's wrong here? Do I need to change something in the setup to handle this? Do you need to see the whole samlp:Response xml? 

TIA
Mike

**Comment by GGross5213** [comment]
@mikevbaker Did you figure this out?

**Comment by mikevbaker** [comment]
No, I was unable to get a resolution for this. I switched from passport-saml to express-saml2 and it went away. I believe the author of express-saml2 says that it's deprecated and people should move to samlify, but I don't see anything written on the express-saml2 home page so I'm not sure.

**Comment by markstos** [comment]
Closing this old support request.
