### ISSUE TITLE
Security issues with xml-encyption -> ejs package

### ISSUE THREAD

**Issue by codecvlt** [bergie/passport-saml#222]
https://snyk.io/vuln/npm:ejs:20161128

Updating xml-encryption package to v0.11.0 should fix the vulnerability.

**Comment by codecvlt** [comment]
https://snyk.io/vuln/npm:node-forge:20150626 also a issue via node-forge dep in xml-encryption.

0.11.0 should fix this as well.

**Comment by markstos** [comment]
This was resolved in the v0.20.0 release, just pushed out.
