### ISSUE TITLE
identifierFormat example for ADFS not correct

### ISSUE THREAD

**Issue by cburatto** [bergie/passport-saml#234]
On the documentation, Usage with Active Directory Federation Services: 

>  {
>     entryPoint: 'https://ad.example.net/adfs/ls/',
>     issuer: 'https://your-app.example.net/login/callback',
>     callbackUrl: 'https://your-app.example.net/login/callback',
>     cert: 'MIICizCCAfQCCQCY8tKaMc0BMjANBgkqh ... W==',
>     authnContext: 'http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows',
>     identifierFormat: null
>   }

However, the metadata generated by `generateServiceProviderMetadata` shows an empty `<NameIDFormat/>`.

This seems to be because the `saml.js` code is:

```
if (options.identifierFormat === undefined) {
    options.identifierFormat = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress";
  }
```
It should probably test for `undefined` and `null`.

**Comment by cburatto** [comment]
Scrap that: it seems you can really NOT send any identified on the request, and the only way to do that is using `identifierFormat = null`. If you simply ommit `identifierFormat `from the options, it will default to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`.

**Comment by ahavriluk** [comment]
Issue #1: When SAML Request is built, identifierFormat = null should not default to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`. According to the spec the default value is `urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified`
Source: http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
I realize changing the lib's default would cause a bunch of issues. So it is a breaking change.

Issue #2: When metadata is generated (generateServiceProviderMetadata method), the statement 
`metadata.EntityDescriptor.SPSSODescriptor.NameIDFormat = this.options.identifierFormat;` line 1221 should be wrapped in `if`:
`if (this.options.indentifierFormat) {
     metadata.EntityDescriptor.SPSSODescriptor.NameIDFormat = this.options.identifierFormat;
}`
