### ISSUE TITLE
How to get profile data on endpoint?

### ISSUE THREAD

**Issue by syntacticsolutions** [bergie/passport-saml#259]
I'm using Okta for authentication of an app that I'm building. I'm going to be adding permissions soon. How do I get user information returned from an endpoint?

**Comment by syntacticsolutions** [comment]
I tried this but I only got an empty object.

```router.get('/get_user_profile_info', (req, res) => {
    return res.status(200).send({
        user: req.user,
        account: req.account
    })
})```

**Comment by markstos** [comment]
This queue is for bug reports and feature requests. Support is not provided here. You can try StackOverflow if you have a concrete question.
