### ISSUE TITLE
Saml2-js is working fine.But I want to use passport-saml. Please help me.

### ISSUE THREAD

**Issue by tusharbudhe0302** [bergie/passport-saml#260]
Config.js :
`Using configuration :  { app: { name: 'Passport SAML strategy example', port: 3000
},
  passport:
   { strategy: 'saml',
     saml:
      { path: '/assert',
        protocol: 'http://',
        host: 'powerbitest.compamyName.com:3000',
        entryPoint: 'http://powerbitest.compamyName.com:3000/',
        issuer: 'https://ssodev.compamyName.com/oamfed/idp/samlv20',
        cert: [Array] } } }
`
passport.js
`module.exports = function (passport, config) {
  const SamlStrategy = require('passport-saml').Strategy;
  console.log('passport-saml config start !\n')
  passport.serializeUser(function (user, done) {
    console.log('passport-saml serializeUser done !\n')
    done(null, user);
  });

  passport.deserializeUser(function (user, done) {
    console.log('passport-saml deserializeUser done !\n')
    done(null, user);
  });

  passport.use(new SamlStrategy(config.passport.saml,
    function (profile, done) {
      console.log('passport-saml check user profile : \n' + profile);
      return done(null,
        {
          id: profile.uid,
          email: profile.email,
          displayName: profile.cn,
          firstName: profile.givenName,
          lastName: profile.sn
        });
    })
  );

};
`

routes.js
`
module.exports = function (app, config, passport) {

  app.get('/', function (req, res) {
    console.log('failureRedirect from passport-saml!');
    if (req.isAuthenticated()) {
      res.render('home',
        {
          user: req.user
        });
    } else {
      res.render('home',
        {
          user: null
        });
    }
  });

  app.get('/test',
    passport.authenticate(config.passport.strategy, { failureRedirect: '/', failureFlash: true }),
    function (req, res) {
      console.log('!!! done');
    	res.redirect('/');
    }
  );

  app.post(config.passport.saml.path,
    passport.authenticate(config.passport.strategy,
      {
        failureRedirect: '/profile',
        failureFlash: true
      }),
    function (req, res) {
      console.log('SAML aurth service 2 called!');
      console.log(req);
      res.redirect('/');
    }
  );

  app.get('/signup', function (req, res) {
    res.render('signup');
  });

  app.get('/profile', function (req, res) {
    console.log('In profile section!');
    if (req.isAuthenticated()) {
      res.render('profile',
        {
          user: req.user
        });
    } else {
      res.redirect('/login');
    }
  });
};
`

### Trying to access

 URL : http://powerbitest.compamyName.com:3000/test

Response : 

URL in browser :

http://powerbitest.compamyName.com:3000/?SAMLRequest=nVPBbuIwEP2VyHcSByiwFqGioNUidbsRZHvYy8pxhtZSbGc9DtC%2FrxPIKocWVZwie57fm3lvMr8%2FqTI4gEVpdELikJL7xRy5Kiu2rN2r3sK%2FGtAFHqaRtYWE1FYzw1Ei01wBMifYbvnzkQ1DyiprnBGmJMFmnZC%2F%2BWwyo9MJzcd5fDceTZsjCZ47Qf%2FCAxFr2Gh0XDt%2FRePZgA4HdJpRyug3Fk%2FC0d34DwnSC%2FWD1IXUL9f7yM8gZD%2ByLB2kv3YZCZaIYJ0XXhmNtQK7A3uQAn5vHxPy6lzFoqgyR7C5dH7o8KV%2BE9xWoTCKjSilEW8JSLD2Vam5a2f4ykNyNpW1o9qem9eH4F3DZNGooJdBNAUc%2BgqR4WoPRSSLKmooD0M6j3pqXZ5Pnn6zTk0pxdsteX43VnH3OToO4%2FZGFoN9C2WguCyXRWEB0btflua4ssAdJMTZGkjUtXbZMijanfPpODjdtHMroypuJTa5wIkL1xnfJ16V3tct7G%2BJ4SpMMNFQ%2B%2BvUf47GFs3KgvCDZZZrrIx1l2g%2B6mdxrn1ix%2F9q%2F79cvAM%3D

I don't what I am doing wrong. Please help me.

**Comment by markstos** [comment]
Support is not provided here. If you have a concrete question, you can try a site like StackOverflow.
