### ISSUE TITLE
Initially saml2 authentication working for my app but suddenly it stops working(I did not change any file).

### ISSUE THREAD

**Issue by kinghemantraj** [bergie/passport-saml#261]
Following steps are happening while authentication
1)User is hitting below url 
https://{our_domain}/forcelogin/{appId}/direct"
2)After hitting above url user will be redirected to below site
https://login.microsoftonline.com/{our_tenantId}/saml2?SAMLRequest={autogenerated code after hitting above url}
3)After entering credentials user is redirecting to below url
https://login.microsoftonline.com/{our_tenantId}/login
4)For 2 min, we can see above url in browser then it show timeout error and gives below url
https://{our_domain}/authreturn

We are using below npms
Passport Modules:
"passport": "0.4.0"
"passport-azure-ad": "3.0.10"
"passport-saml": "0.15.0"

**Comment by markstos** [comment]
If you've believe you've found a bug in `passport-saml`, add a test case to the test suite which triggers it.
