### ISSUE TITLE
[v0.33.0] - Where has `disableRequestedAuthnContext` been documented ?

### ISSUE THREAD

**Issue by cadesalaberry** [bergie/passport-saml#263]
In the release, the following is mentioned:

> - Add support for setting the strategy name, allowing multiple saml target configurations (Thanks to @markstos)
> - document that disableRequestedAuthnContext:true helps with Active Directory (Thanks to @markstos)
> - document that cert: refers to the signature certification, not the encryption certificate. (Thanks to @markstos)

Where has `disableRequestedAuthnContext` been documented ?

I looked through the commits be could not find it.

Cheers,

**Comment by markstos** [comment]
@cadesalaberry searching the README or through the repo will find it: https://github.com/bergie/passport-saml/search?utf8=%E2%9C%93&q=disableRequestedAuthnContext&type=

**Comment by cadesalaberry** [comment]
@markstos  Yes, I was aware. It seemed that more documentation was added relative to ADFS in this release; Leaving me wondering what it said.

So in my understanding, nothing is new? What does this line refer to?

Cheers,

**Comment by markstos** [comment]
@cadesalaberry It was documented in the release actually shipped, but it looks like I hadn't pushed to Github. Thanks for noticing.

Here's the commit you are looking for:

https://github.com/bergie/passport-saml/commit/8f1fe3269b5e4497d97a5534f5236a07140c0560
