### ISSUE TITLE
authnRequestBinding: 'HTTP-POST' failed.

### ISSUE THREAD

**Issue by tusharbudhe0302** [bergie/passport-saml#264]
@gbraad @bergie @twada @markstos @teppeis @nkovalenko-sc
 Meta Data File: 
`<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://usdf13v0412_dev_tushar:3000/" ID="https://usdf13v0412_dev_tushar_3000/">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <KeyDescriptor>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>+szp9khRZ/cg5wXS7WZa91yzJcjVVnTa+QOdtF
		</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"/>
    </KeyDescriptor>
    <NameIDFormat/>
    <AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://usdf13v0412_dev_tushar:3000/assert"/>
  </SPSSODescriptor>
</EntityDescriptor>
`
 It's working in case of redirect (I am removing from configuration skipRequestCompression : false, authnRequestBinding: 'HTTP-POST'). It's goinmg to login page,but not allow to reset password. Because **Referer** tag missing from.
"Referer" :https://usdf13v0412_dev_tushar:3000/login

If I do http-post below tags are missing :
>  SigAlg:http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
> Signature:XYZ

`saml_config: {
      callbackUrl: 'https://usdf13v0412_dev_tushar:3000/assert',
      path: '/assert',
      protocol: 'https://',
      host: 'usdf13v0412_dev_tushar:3000',
      entryPoint: 'https://ssodev.XYZ.com/oamfed/idp/samlv20',
      issuer: 'https://usdf13v0412_dev_tushar:3000/',
      cert: fs.readFileSync("./keys/saml/cert-idp.pem", 'utf-8'),
      privateCert: fs.readFileSync('./keys/saml/key-service-genrateMeataData.key', 'utf-8'),
      decryptionPvk: fs.readFileSync('./keys/saml/certificate-service-genrateMeataData.OneLine.crt', 'utf-8'),
      signatureAlgorithm: 'sha256',
      identifierFormat: null,
      validateInResponseTo: false,
      disableRequestedAuthnContext: true,
      forceAuthn: true,
      skipRequestCompression : false,
      authnRequestBinding: 'HTTP-POST',
    }`
This got missed from Request headers so I am getting Error Page.  Please let me know If I am missing anything.

**Comment by markstos** [comment]
This appears to be a support request, which should be asked on StackOverflow, not here. If you believe you've found a bug in passport-saml, please let us know, preferably by adding a test case to the test suite which illustrates the failure.

**Comment by tusharbudhe0302** [comment]
Thanks @markstos  for reply. I not saying it's bug. I just need information. Please let me know why meta data is missing signature tag. Please help me with this. I will really appreciate.
