### ISSUE TITLE
SignatureValue not being checked?

### ISSUE THREAD

**Issue by einarjohnson** [bergie/passport-saml#268]
Hi.
I am trying to verify a SAML2 response by sending a POST request to my SP setup. The token has a SignatureValue in it. It seems that the validateSignature function inside passport-saml/lib/passport-saml/saml.is never finds the needed signature object and returns false
`var xpathSigQuery = ".//*[local-name(.)='Signature' and " +
                      "namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']";

  var signatures = xpath(currentNode, xpathSigQuery);

  // This function is expecting to validate exactly one signature, so if we find more or fewer
  //   than that, reject.
  if (signatures.length != 1)
    return false;`

My token looks  like this
`<?xml version="1.0" encoding="UTF-8"?>
<Response Destination="http://www.digidoktor.is/islykill" ID="_91e2d0bf-d565-46d9-9ca6-c173c6995765" IssueInstant="2018-03-16T17:31:57.5379282Z" Version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Issuer>Islyklar</Issuer>
	<Signature>
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
			<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
			<Reference URI="">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<DigestValue>3IHF2lkJL3gxyJ99C7z1lZGI6SBT5U9ZfwV3TBQNl4M=</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>CD7KFLp3j0UizzWRTri/pOX+5nfai0BOmT/5KMwGOWViIyX74j/WXI7XdVjTS/Zfiziepimbo8eiWFKtgYlxLIzMHoICK8WYz+r7bZGdecvHV6xeTlVQcwDwna6grrOGzzvrWbrbiO8IDRld459bGg1KKqM0AM3Zpr/Kagnce+5egRGDeAWLPwGWyHfLF37BvAweZ9+sYV4LBEGXtILkgJqxQWsh/Yfe8qz49hxaIp3E5YYmvtBqRSfwyPJHjgGYeioz1JanO5v5hHihas+ZKCK7SRRY6QojY0wChB8pxbpivCwvZ3/BOY8lzdtpQryAmmQkPmB0HZa9yG3h6LGvkg==</SignatureValue>
		<KeyInfo>
			<X509Data>
				<X509Certificate>MIIGDDCCBPSgAwIBAgICHRwwDQYJKoZIhvcNAQEFBQAwgZIxCzAJBgNVBAYTAklTMRMwEQYDVQQFEwo1MjEwMDAyNzkwMRYwFAYDVQQKEw1BdWRrZW5uaSBlaGYuMSMwIQYDVQQLExpVdGdlZmFuZGkgYnVuYWRhcnNraWxyaWtqYTEWMBQGA1UECxMNTWlsbGlza2lscmlraTEZMBcGA1UEAxMQVHJhdXN0dXIgYnVuYWR1cjAeFw0xNjA3MTQxNTExMzdaFw0xODA3MTQxNTExMzdaMIHCMQswCQYDVQQGEwJJUzEeMBwGA1UECgwVw55qw7PDsHNrcsOhIMONc2xhbmRzMRgwFgYDVQQLEw9CdW5hZGFyc2tpbHJpa2kxJTAjBgNVBAsMHFVuZGlycml0dW4gZcOwYSBhdcOwa2VubmluZyAxHTAbBgkqhkiG9w0BCQEWDnZlcmtAaXNsYW5kLmlzMRMwEQYDVQQFEwo2NTAzNzYwNjQ5MR4wHAYDVQQDExVJbm5za3JhbmluZyBJc2xhbmQuaXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGunlc4jwRyE+W0MiWfT6sdXvSMwsRTg3rTlw50/rbjUuGGMhYerYFl7itc/i0ZsMbGetq8Z/BFnEIqhY/zsHFk/DRRBLze6HIOLYAqMn9LEGVhquzwfQW8dCB7LEr+W/YdbdTp6vkbiE2h2PDtb8VYpH103Oa8FzplVKSwZLSRhiJAeI9Rs7Z+2SlNhTje9tUxzWInxtSTmnjB/YXISJgfwtrt/5Ws1Z0CX/VgQ4+ZsnmN7t+8AeDwv41SkJCjT7R1Vn5IKm3QNBzS+q414H4eCa1O2my7NehvLBvrjeHegsP4mtYp8bNJ6W/IxsXDLY3AKe2IM72+AAytXlMONahAgMBAAGjggI4MIICNDAMBgNVHRMBAf8EAjAAMIIBHAYDVR0gBIIBEzCCAQ8wggELBglggmABAgEBBAEwgf0wgcQGCCsGAQUFBwICMIG3GoG0VGhpcyBjZXJ0aWZpY2F0ZSBpcyBpbnRlbmRlZCBmb3IgZGlnaXRhbCBzaWduYXR1cmVzIGFuZCBhdXRoZW50aWNhdGlvbi4gVGhpcyBjZXJ0aWZpY2F0ZSBmdWxmaWxzIHRoZSByZXF1aXJlbWVudHMgb2Ygbm9ybWFsaXplZCBjZXJ0aWZpY2F0ZSBwb2xpY3kgKE5DUCkgZGVmaW5lZCBpbiBFVFNJIFRTIDEwMiAwNDIuMDQGCCsGAQUFBwIBFihodHRwOi8vY3AuYXVka2VubmkuaXMvdHJhdXN0dXJidW5hZHVyL2NwMHMGCCsGAQUFBwEBBGcwZTAjBggrBgEFBQcwAoYXaHR0cDovL29jc3AuYXVka2VubmkuaXMwPgYHYIJgAgFjBoYzaHR0cDovL2NkcC5hdWRrZW5uaS5pcy9za2lscmlraS90cmF1c3R1cmJ1bmFkdXIucDdiMAsGA1UdDwQEAwIF4DAfBgNVHSMEGDAWgBRv7NsRLAEDaxtgrrb4aNlAAc2OODBCBgNVHR8EOzA5MDegNaAzhjFodHRwOi8vY3JsLmF1ZGtlbm5pLmlzL3RyYXVzdHVyYnVuYWR1ci9sYXRlc3QuY3JsMB0GA1UdDgQWBBTXlBUp1axlTP9Rp2js7gSEmHKVzDANBgkqhkiG9w0BAQUFAAOCAQEABbDwqym5k1pmai/UL49pceeJnWSTvpZOabAYXOb/CeOM6iombgSgi/F8nXtZ49QCAZEdlB7S+jKL/6btqnWvE3FtaZpDzU1LdkzvUlJSYJlWCRgQV8g2uLz78QibychcIjlT2j0tx32TTg9kd64KX+k7/YjP+QJ1rpPkvWT7DNdJTrnLhCE01/qgGza2D+3c7Tav7WpqSv1CN7AY0RtDsEDBoH4os+5SRCX0+oOQ7ucv+nbaOYggzz06w7yfUdUQtrxS97fJwuH7hspD50lRdSlzKR38GPcL9E54OMz6Znw8ntw2htNZ1p0K/97sYJUUaHJWSM7u5655JyvpeEjKeA==</X509Certificate>
			</X509Data>
		</KeyInfo>
	</Signature>
	<Status>
		<StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
	</Status>
	<Assertion ID="_990b2793-90b5-4cbe-a85e-6a93234dd790" IssueInstant="2018-03-16T17:31:57.5379282Z" Version="2.0">
		<Issuer>Islyklar</Issuer>
		<Subject>
			<NameID NameQualifier="island.is"/>
			<SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<SubjectConfirmationData Address="10.121.57.25" NotOnOrAfter="2018-03-16T17:36:57.5379282Z" Recipient="http://www.digidoktor.is/islykill"/>
			</SubjectConfirmation>
		</Subject>
		<Conditions NotBefore="2018-03-16T17:31:47.5379282Z" NotOnOrAfter="2018-03-16T17:36:57.5379282Z">
			<AudienceRestriction>
				<Audience>www.digidoktor.is</Audience>
			</AudienceRestriction>
		</Conditions>
		<AuthnStatement AuthnInstant="2018-03-16T17:31:57.5379282Z">
			<SubjectLocality Address="212.30.225.139"/>
			<AuthnContext>
				<AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:TLSClient</AuthnContextClassRef>
			</AuthnContext>
		</AuthnStatement>
		<AttributeStatement>
			<Attribute FriendlyName="Kennitala" Name="UserSSN" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">2402596139</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="Nafn" Name="Name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">Bragi Leifur Hauksson</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="Auðkenning" Name="Authentication" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">Rafræn skilríki</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="IPTala" Name="IPAddress" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">10.121.57.25</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="KennitalaMóttakanda" Name="DestinationSSN" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">1106773249</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="NotandaStrengur" Name="UserAgent" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xsi:type="xsd:string">Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36</AttributeValue>
			</Attribute>
		</AttributeStatement>
	</Assertion>
</Response>`

Also, my IDP posts this saml response to my POST binding using a variable named "_token_" and not "_SAMLResponse_". Can I configure this somehow using the framework?

**Comment by markstos** [comment]
Support requests are better addressed through StackOverflow with the `passport-saml` tag. No one is monitoring this queue to answer support requests. 

https://stackoverflow.com/questions/tagged/passport-saml
