### ISSUE TITLE
custom callback is not getting called

### ISSUE THREAD

**Issue by dyaacov** [bergie/passport-saml#280]
Hi All,
I'm trying to get the ADFS respone (redirect) in my custom callback but it never gets called.
any idea?

app.get('/sso/login', (req, res, next) => {
  passport.authenticate('saml', (err, user, info, status) => {
    if (err) {
      return next(err)
    }
    if (!user) {
      return res.redirect('/signin')
    }
    res.redirect('/account')
  })(req, res, next)
})

**Comment by markstos** [comment]
Questions are better asked on StackOverflow the the passport-saml tag. No one is monitoring the bug tracker to answer support requests. 

https://stackoverflow.com/questions/tagged/passport-saml

**Comment by illya-anyvision** [comment]
If someone encounter this issue make sure you use the same middleware in your callback route as well
` passport.authenticate('saml'),`
