### ISSUE TITLE
No certificate in metadata?

### ISSUE THREAD

**Issue by affanshahid** [bergie/passport-saml#293]
New to SAML authentication, most SP metadata files I've seen and the one I generated using saml2-js has the public cert inside the metadata, but when I try to generate the metadata using passport-saml it lacks the entries for the certificate.

Probably I'm doing something wrong:
```js

app.use(passport.initialize());
const s = (new SamlStrategy(
  {
    path: '/assert',
    host: 'localhost:4000',
    entryPoint: 'http://localhost:8080/auth/realms/test/protocol/saml',
    privateCert: fs.readFileSync('./config/private.pem', 'utf-8'),
    cert: 'abcdef__IDP_CERT__abcefg'
  },
  function(profile, done) {
    done(null, { username: 'test' });
  })
);

const xml = s.generateServiceProviderMetadata(fs.readFileSync('./config/server.crt', 'utf-8'));
```

This is the output XML:
```xml
<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="onelogin_saml" ID="onelogin_saml">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:4000/assert"/>
  </SPSSODescriptor>
</EntityDescriptor>
```

**Comment by srmaharjan** [comment]
I think you also need to supply decryptionPvk option in order to get certificate information in metadata
app.use(passport.initialize());
const s = (new SamlStrategy(
  {
    path: '/assert',
    host: 'localhost:4000',
    entryPoint: 'http://localhost:8080/auth/realms/test/protocol/saml',
    privateCert: fs.readFileSync('./config/private.pem', 'utf-8'),
    decryptionPvk:fs.readFileSync('./config/server.crt', 'utf-8'),
    cert: 'abcdef__IDP_CERT__abcefg'
  },
  function(profile, done) {
    done(null, { username: 'test' });
  })
);

const xml = s.generateServiceProviderMetadata(fs.readFileSync('./config/server.pem', 'utf-8'));

**Comment by markstos** [comment]
Please direct support requests to StackExchange rather than this bug tracker.
