### ISSUE TITLE
Tested and working idp's 

### ISSUE THREAD

**Issue by sp90** [bergie/passport-saml#294]
So the documentation states: 

> Passport-SAML has been tested to work with Onelogin, Okta, Shibboleth, SimpleSAMLphp based Identity Providers, and with Active Directory Federation Services.

But i wanted to start a tread where people could give feedback if they found it working with these and other not noted services

Remember to check if its been stated already, then if you have it working give it a 👍 and if you have it not working please use the 👎  instead, that way we keep the issue short and tidy

**Comment by sp90** [comment]
Onelogin is working 👍

**Comment by markstos** [comment]
I've tested it with Onelogin, Okta, ADFS and many Shibboleth servers.

This module is generally spec-compliant, so it should work with spec-compliant servers. However, it has some missing features. The issue I've run into is not so much with different providers, it's when the idP wants to use some feature that's missing or not well supported here.  So far I've got about a dozen or so integrations working with it. The one missing feature *I* needed was better support for multiple SAML providers configured at once, and I patched the module to improve that support. 

The existing issues posted in this issue tracker provide a good sense of the places where people have run into rough edges.

**Comment by sp90** [comment]
I'm using this branch to dynamically handle configs:
https://github.com/bergie/passport-saml/pull/276

**Comment by markstos** [comment]
I'm closing this. Just because it works for one person with their IdP in one configuration isn't a guarantee it will work for you with your configuration. A more useful reference could be a list of SAML spec features that we support, or a list of SAML features that are known to be missing.   

Also, we have a wiki for collaborative documentation.
