### ISSUE TITLE
Unexpected deletion of Strategy config.name property during creation

### ISSUE THREAD

**Issue by josnidhin** [bergie/passport-saml#296]
I recently updated from `0.32.1` to `0.35.0`. This caused by application to fail with the following error message
`Authentication strategies must have a name`

After investigation, I found the following code was added in `0.33.0` https://github.com/bergie/passport-saml/blob/v0.33.0/lib/passport-saml/strategy.js#L17:L23

```
  // Customizing the name can be useful to support multiple SAML configurations at the same time.
  // Unlike other options, this one gets deleted instead of passed along.
  if  (options.name) {
    this.name  = options.name;
    delete options.name;
  }
  else {
    this.name = 'saml';
}
```
I was already using a name property in the config so that I can setup multiple SAML strategies, sample code shown below

```
    let samlStrategy = new SAMLStrategy(conf, (profile, done) => {
      // some code here
    });

    passport.use(conf.name, samlStrategy);
```

The above code now fails because for the change made in `0.33.0` and I had to solved this issue by making a clone of the `conf` object and passing the clone when creating the strategy.

Question: Shouldn't the module take care of creating the clone if it is going to delete properties of parameters that is been passed to it?

**Comment by markstos** [comment]
@josnidhin You are right-- it would be a better design to clone the `options` passed in and delete from that. Would you be willing to put together a PR to improve this?

**Comment by markstos** [comment]
@josnidhin I'm checking again to see if you are willing to fix this issue. Thanks.

**Comment by markstos** [comment]
@josnidhin I'm planning a new release within the next 10 days, and this improvement would be welcome.

**Comment by cjbarth** [comment]
@markstos I would like to see this get fixed before a 1.0 release. I see that you added the comment explaining that `options.name` should not get passed along. Could you clarify _why_ it shouldn't get passed along?

**Comment by cjbarth** [comment]
I understand that part of it, but I'm wondering why `options.name` is deleted in the first place.

**Comment by josnidhin** [comment]
@markstos Sorry for the late reply was on vacation. 

I can help with this bug but as @cjbarth asked why do we have we have to delete that property.

If it needs to be deleted then the options object will have to be cloned and the way to do it will depend on the Node versions to supported. Currently the `package.json` says Node Engine `>=` 4 do we have to support 4?. If its 6 and above the we can use the `Object.assign` else I am thinking of something like `JSON.parse(JSON.stringify(options))`.

**Comment by markstos** [comment]
@cjbarth  Oh. :) I wrote that code in: https://github.com/bergie/passport-saml/commit/6e2418bae01b98dc982a3d37a543ef7ea079fd76

The reason is that "options.name" was not passed along before, and I didn't want to modify that behavior.   

At the time, I needed to be able to connect to multiple IdPs, and giving each IdP a custom name here helped me be do that. 

For more context, here's the issue that led to the original change.  https://github.com/bergie/passport-saml/commit/6e2418bae01b98dc982a3d37a543ef7ea079fd76

**Comment by markstos** [comment]
@josnidhin We will support all Node LTS releases that are actively maintained. A PR is welcome to bump the minimum supported version to 6, as Node 4 has been EOLed. 

I have not looked at the effect of continuing to pass `options.name` on through to the next call:

```
 this._saml = new saml.SAML(options);
```

You are welcome to investigate, but deleting it and not passing is definitely safe as that's the original behavior.

**Comment by cjbarth** [comment]
@markstos Interestingly enough, I have had to federate against multiple IdP's as well and leveraged the ability to set different names to get it done and I'm on 0.15, before this changed landed. Thus, I'm not sure that this was strictly required to get everything working. I note that `options.name` was always being passed down to the `saml.SAML()` ctor and that behavior only stopped with this PR.

```function Strategy (options, verify) {
  if (typeof options == 'function') {
    verify = options;
    options = {};
  }

  if (!verify) {
    throw new Error('SAML authentication strategy requires a verify function');
  }

  this.name = 'saml'; // if options.name was set at this point, it was never unset.

  passport.Strategy.call(this);

  this._verify = verify;
  this._saml = new saml.SAML(options);```

I thus feel that the only change that we need to make would be to remove the line to delete `options.name`. Is there something I'm missing? In fact, There doesn't seem to be mush use for `this.name` either.

**Comment by markstos** [comment]
@cjbarth  About two weeks after I commited this change, someone from the `passport` project left a comment explaining how I could accomplish the same thing using an undocumented feature of `passport`. You can see my comment and the answer here:

https://github.com/jaredhanson/passport/pull/606#issuecomment-365710590

By that point, I had already released the new version of `passport-saml` with the change.  However, now it's clear the change wasn't necessary and was clearly broken for a common case that led to this bug report. So another option we have is just revert the bad commit. I can add some documentation on how to use the undocumented  2-argument call to `passport.use()` instead.

This might be considered a breaking change, but our next release is planned to contain some other breaking changes anyway.

**Comment by cjbarth** [comment]
In that case, since this change introduced a bug, I'm in favor of reverting it and updating the documentation. I must be using the undocumented way too, though I spent a lot of time reading the source code to build my code to use this library, so I probably missed that it wasn't documented:) Now is a good time to make such breaking changes, however, would this really be a breaking change since we'd just be reverting to previous behavior?... Well, I suppose we did a breaking change, and this would be a breaking change to undo that breaking change... Anyway 1.0 here we come!

**Comment by markstos** [comment]
It's only breaking for the small (very small?) number of people who used the new feature. I'll handle the revert and related docs. Assigning to myself.

**Comment by cjbarth** [comment]
@markstos Is this still an open issue?

**Comment by markstos** [comment]
Yes, we still have the "delete options.name" line.

I think the solution at this point is to clone `options` so we are deleting from a copy of the object and don't have  a pass-by-reference bug. It would also be good to add an automated test for the bug. 

Should be a small task.

**Comment by cjbarth** [comment]
I thought that we were going to remove that line based on the last discussion on this matter. Have I missed something?

**Comment by markstos** [comment]
I looked again at the commit where I added the line:

https://github.com/bergie/passport-saml/commit/6e2418bae01b98dc982a3d37a543ef7ea079fd76

I think you are right-- I think we just don't need the line and removing the "delete" line would be considered a bug fix. I'll do that now.
