### ISSUE TITLE
fetch redirection for standalone clients

### ISSUE THREAD

**Issue by Johnz86** [bergie/passport-saml#297]
We are using our custom implementation of strategy provided by this library. The reason is our standalone javascript client on separate server is not able to get location redirection on fetch when HTTP method is 304. Access to headers is blocked by browser based on fetch specification when HTTP redirect methods are used.  To fix this we made a small change for one line in strategy.js. Instead of this: 
```js
  function redirectIfSuccess(err, url) {
    if (err) {
      self.error(err);
    } else {
      self.redirect(url);
    }
  }
```
we do this:
```js
   function redirectIfSuccess(err, url) {
     if (err) {
       self.error(err);
     } else {
       self.redirect(url, 401);
     }
   }
```

Would it be possible to improve your solution and allow customization of redirect HTTP method?

**Comment by markstos** [comment]
[HTTP status code 401 is not valid for redirection](https://stackoverflow.com/questions/8775593/is-it-possible-to-send-a-401-unauthorized-and-redirect-with-a-location). It may happen to work in your case, but I'm going to support it here.

In #295, @xylude proposed splitting out the SAML library module from the passport layer, giving users who want it full flexibility to customize how they use the SAML library. I suggest working on that task as one possible solution, or looking for another place in your code to solve your problem.
