### ISSUE TITLE
Decrypting SAML response from IDP is inconsistent

### ISSUE THREAD

**Issue by whatch** [bergie/passport-saml#307]
I have a working configuration, against a testing IDP, where I'm successfully decrypting the returned assertions. Updating the configuration to a different IDP endpoint, but using the same SP key/cert, and a different public cert from the IDP, and I keep getting this error:

> Error: Invalid PEM formatted message.
>     at Object.pem.decode (/opt/app/node_modules/node-forge/lib/pem.js:185:11)
>     at Object.pki.privateKeyFromPem (/opt/app/node_modules/node-forge/lib/pki.js:52:23)
>     at decryptKeyInfoWithScheme (/opt/app/node_modules/xml-encryption/lib/xmlenc.js:186:25)
>     at decryptKeyInfo (/opt/app/node_modules/xml-encryption/lib/xmlenc.js:176:14)
>     at Object.decrypt (/opt/app/node_modules/xml-encryption/lib/xmlenc.js:129:24)
>     at Promise.post (/opt/app/node_modules/q/q.js:1181:36)
>     at Promise.promise.promiseDispatch (/opt/app/node_modules/q/q.js:808:41)
>     at /opt/app/node_modules/q/q.js:1411:14
>     at runSingle (/opt/app/node_modules/q/q.js:137:13)
>     at flush (/opt/app/node_modules/q/q.js:125:13)
>     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

However, I can take the same saml response that results in the above error, and the configured privateCert/decryptionPvk I'm using in the configuration, run that through https://www.samltool.com/attributes.php and it decrypts fine. I"m baffled as to what the difference could be.

**Comment by whatch** [comment]
closing this, as it was not really a passport issue, but rather a misunderstanding between SP and IDP, and a faulty decryption config on the SP's part. I did however determine that you must pass the decryptionPvk config the output from fs.readFileSync(your.pem, 'utf-8'), and am not able to use the object arg format like I can do with the privateCert. This does seem inconsistent, as I'm not sure how you'd be able to use a key with a password for the decryptionPvk in that case, but, passing the object did not work for me, and I had to just pass the read file .pem directly to that option. Hope this helps somebody.

**Comment by ssbrewster** [comment]
You can use the "object arg" format as long as you keep the header and footer for the key e.g.:
```
{
    decryptionPvk: '-----BEGIN PRIVATE KEY-----MDHF....gG==-----END PRIVATE KEY-----'
}
```
This is useful if you want to read the key in from a secure store.
