### ISSUE TITLE
Request release 0.36

### ISSUE THREAD

**Issue by fluggo** [bergie/passport-saml#319]
I'd like to request a new release of this module. There are some recent features that I'd like to take advantage of, particularly f82d14190e44dee2eb40585e220dbab3234ccaf8 from @cjbarth.

Please, pretty please, can we have a new release?

**Comment by toddbu** [comment]
+1. We need that exact same commit

**Comment by jasonbw** [comment]
+1 I'm looking for to https://github.com/bergie/passport-saml/commit/f6b1c885c0717f1083c664345556b535f217c102

**Comment by markstos** [comment]
I've now released 1.0.0. @fluggo @toddbu @jasonbw 

Release notes are here: https://github.com/bergie/passport-saml/releases/tag/v1.0.0

Thanks to @elahti @stavros-wb @cjbarth @sibelius.
