### ISSUE TITLE
Error: Invalid signature

### ISSUE THREAD

**Issue by huineng** [bergie/passport-saml#324]
Could you please tell me what breaking change you have introduced since i've upgraded to 1.0.0 from 0.35.0 ?

this package was running correctly since several months until this release update.
i have no clue what has changes or what caused this 

thanks

```
Error: Invalid signature
    at /home/app/node_modules/passport-saml/lib/passport-saml/saml.js:609:15
    at _fulfilled (/home/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/app/node_modules/q/q.js:816:13)
    at /home/app/node_modules/q/q.js:624:44
    at runSingle (/home/app/node_modules/q/q.js:137:13)
    at flush (/home/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

**Comment by huineng** [comment]
I guess the reason is the crypto-xml upgrade see https://github.com/yaronn/xml-crypto/issues/158 and https://github.com/yaronn/xml-crypto/issues/164

**Comment by huineng** [comment]
got it solved https://github.com/yaronn/xml-crypto/issues/167

**Comment by phof** [comment]
I had the same issue after upgrading to passport-saml 1.0.0; downgrading to xml-crypto 0.10.1 solved it.

```
"resolutions": {
  "passport-saml/xml-crypto": "0.10.1"
}
```

cc/ @huineng @LoneRifle @markstos FYI

**Comment by christiaanwesterbeek** [comment]
I had the same issue with passport-saml 1.0.0  and I can confirm that adding this to package.json fixed the problem.

```
"resolutions": {
  "passport-saml/xml-crypto": "0.10.1"
}
```

And the following does not
```
"resolutions": {
  "passport-saml/xml-crypto": "1.1.1"
}
```

**Comment by LoneRifle** [comment]
Hello @christiaanwesterbeek @phof - could I trouble either of you to test this against 1.0.1 of xml-crypto to see if that works? The cause of the issue might be down to what @huineng raised in yaronn/xml-crypto#167 ; I just want someone to confirm this is the case.

If you can also confirm that the fix @huineng proposed there would resolve the issue, I'll take a PR.

**Comment by christiaanwesterbeek** [comment]
@LoneRifle I just tested it. A resolution with 1.0.1 of `xml-crypto` works too. I've looked into trying what  @huineng proposed in https://github.com/yaronn/xml-crypto/issues/167 . Unfortunately It's not enough info for me. I'll elaborate a bit over there...

**Comment by phof** [comment]
@LoneRifle Confirmed xml-crypto 1.0.1 works; I'll take a look at yaronn/xml-crypto#167

**Comment by LoneRifle** [comment]
Let's continue the discussion there.

**Comment by paglasoft** [comment]
It is still a nightmare not working, I tried downgrading(0.10.12) and upgrading(1.1.2) .. still the same error.
`
Error: Invalid signature
--
  | at /opt/app-root/src/node_modules/passport-saml/lib/passport-saml/saml.js:609:15
  | at _fulfilled (/opt/app-root/src/node_modules/q/q.js:854:54)
  | at /opt/app-root/src/node_modules/q/q.js:883:30
  | at Promise.promise.promiseDispatch (/opt/app-root/src/node_modules/q/q.js:816:13)
  | at /opt/app-root/src/node_modules/q/q.js:624:44
  | at runSingle (/opt/app-root/src/node_modules/q/q.js:137:13)
  | at flush (/opt/app-root/src/node_modules/q/q.js:125:13)
  | at process._tickCallback (internal/process/next_tick.js:61:11)

`

**Comment by markstos** [comment]
@paglasoft yelling in a headline style is not welcome. You _are_ welcome to pay someone to look into your issue or use a different module if you can't resolve it yourself. Yelling at the volunteers helping to maintain this module is counterproductive.

**Comment by paglasoft** [comment]
Hi Team,

I did not meant to yelling. My apologies If it is taken that way. Thanks
for all the hardwork and excellent module.

Regards

**Comment by etyp** [comment]
@huineng @christiaanwesterbeek were all attempts failing once upgraded to 1.0.0 or just some?

I'm running into this issue now when testing from [Okta's testing tool](http://saml.oktadev.com/), but even if I downgrade to 0.35.0 and ensure xml-crypto is at 0.10.1 I get the Invalid Signature error.

Maybe I'm misunderstanding the thread though :)

**Comment by christiaanwesterbeek** [comment]
Since the "xml-crypto" dependency is now "^1.1.4" and 1.1.4 is not causing this bug anymore, this issue might just as well be closed.

**Comment by christiaanwesterbeek** [comment]
@huineng Can you confirm that your problem is now gone after upgrading?
