### ISSUE TITLE
Restore redirect binding support from passport-saml-too branch.

### ISSUE THREAD

**Issue by ploer** [bergie/passport-saml#33]
See https://github.com/bergie/passport-saml/commit/6f2087e2aa8f14953ec454e82e9882e28ba90da3, in which it was removed.

However, in order to restore this, will need to add signature verification support, which is not in the passport-saml-too code.

**Comment by markstos** [comment]
If anyone from this thread is still around and interested, #277 proposes to address this.

**Comment by markstos** [comment]
Considering this resolved by #277
