### ISSUE TITLE
AssertionConsumerServiceURL always non secure http and ignore protocol:'https://'

### ISSUE THREAD

**Issue by paglasoft** [bergie/passport-saml#349]
All Url's except  AssertionConsumerServiceURL always change to 'http' which mismatch with meta data send to Identity Provider.

> production: {
    app: {
      name: 'SAML Based Authentication',
      port: process.env.OPENSHIFT_NODEJS_PORT || 8080
    },
    passport: {
      strategy: 'saml',
      saml: {
        callbackUrl:process.env.SAML_CALLBACK,
        path: '/auth/saml/callback',
        entryPoint:  process.env.SAML_ENDPOINT,
        issuer: process.env.SAML_ISSUER,
        identifierFormat:'',
        cert: process.env.SAML_IDP_CERT,
        protocol:'https://'
      }
    }
  }

**Comment by markstos** [comment]
@paglasoft Please provide a test for the test suite which reproduces the issue.

**Comment by paglasoft** [comment]
@markstos  thank you for the quick reply. I was following the example which had missing protocol settings. Once i added protocol:''https://' it worked.
