### ISSUE TITLE
InResponseTo is not valid in logout

### ISSUE THREAD

**Issue by VilleMiekkoja** [bergie/passport-saml#351]
Logout does not set InResponseTo to cache. But then expects it to be found in logout-callback if passport.authenticate is applied there (as should). This results in error:

`InResponseTo is not valid`

**Comment by stavros-wb** [comment]
@VilleMiekkoja are you using MultiSamlStrategy?

**Comment by VilleMiekkoja** [comment]
@stavros-wb No.

**Comment by VilleMiekkoja** [comment]
Opened PR for this: https://github.com/bergie/passport-saml/pull/356

**Comment by markstos** [comment]
Related PR has been merged.
