### ISSUE TITLE
passReqToCallback: true not working on MultiSamlStrategy

### ISSUE THREAD

**Issue by gavinbelson** [bergie/passport-saml#358]
In the conf below, I am using the   `,passReqToCallback: true` .. then adding `req` to the callback function.  (this is how this option works on passport-facebook)

I am getting:
TypeError: done is not a function

If I remove `req` from the callback it works again but then I don't have the `req` object that I need to use with the `profile`

```
const conf = {
  path: '/login/callback',
  entryPoint: 'https://something',
  issuer: 'https://something',
  cert: fs.readFileSync('key.pem', 'utf-8'),
  decryptionPvk: fs.readFileSync('saml.pem', 'utf-8')
  ,logoutUrl: 'https://something'
  ,passReqToCallback: true
};

passport.use(new MultiSamlStrategy({
    getSamlOptions: function(request, done) {
      return done(null, conf);
    }
  },
  function(req, profile, done) {  //taking out req here will make this work but won't pass the req
    var user = profile;
    return done(null, user);
  })
);
```

**Comment by gavinbelson** [comment]
Just checked and this does work if I use `SamlStrategy` instead of `MultiSamlStrategy`

**Comment by stavros-wb** [comment]
@gavinbelson can you try:
```js
passport.use(new MultiSamlStrategy({
    passReqToCallback: true,
    getSamlOptions: function(request, done) {
      return done(null, conf);
    }
  },
  function(req, profile, done) {  //taking out req here will make this work but won't pass the req
    var user = profile;
    return done(null, user);
  })
);
```

**Comment by gavinbelson** [comment]
Lifesaver. Thanks man, this works.

I believe in the docs it says to do:
`return done(null, provider.configuration);`

Maybe, this should be added to the docs somewhere?

**Comment by markstos** [comment]
If the docs need improvement, a PR is welcome. Note there will be a bug-fix for Multi-SAML in the next release.

**Comment by cjbarth** [comment]
@gavinbelson I'm not sure what part of the documentation you're referring to. The documentation for MultiSamlStrategy seems good to me: https://github.com/bergie/passport-saml#configure-strategy-for-multiple-providers. It matches what @stavros-wb suggested.

**Comment by gavinbelson** [comment]
@cjbarth  I added a PR to add @stavros-wb 's suggestion to the README

**Comment by markstos** [comment]
Related PR was merged.
