### ISSUE TITLE
Missing function getSamlResponseXml

### ISSUE THREAD

**Issue by PeterAlb** [bergie/passport-saml#369]
Just realized that the function "getSamlResponseXml" on master is not available in the current release.

Master:
https://github.com/bergie/passport-saml/blob/48ac6558ef57edba8ed90fae53833e17b4b0d0ed/lib/passport-saml/saml.js#L1048

Release:
https://github.com/bergie/passport-saml/blob/677424cf2f594344e4e70bec0be2d7591a60e089/lib/passport-saml/saml.js#L1025

The docs are displaying wrong informations about the current available functions on the Profile-Object because of that, too.

Could you look into it?

**Comment by josecolella** [comment]
@PeterAlb I created the PR to master. It has been merged master. It's waiting for a release by @markstos

**Comment by markstos** [comment]
I just merged a fix for failing tests today which were blocking release. We are close!

@PeterAlb Also, it never a bug for the latest document in Git to differ from what is released. If you want documentation that matches the shipped code, check the documentation that's actually shipped, or what appears on npmjs.org that matches the version you are using. Github is for development and can be expected to be ahead of the released code on a regular basis.

**Comment by PeterAlb** [comment]
Thanks for the clarification and the work on the next release ;)
