### ISSUE TITLE
Integration with Citrix Netscaler and certificates

### ISSUE THREAD

**Issue by AlbertoWeinrichter** [bergie/passport-saml#370]
Hello all

We are trying to use Citrix Netscaler as IDP and we are having some trouble finding a configuration that works.

out configuration looks like this on passport-saml
  {
    entryPoint: 'IDP ENTRY POINT URL',
    callbackUrl: 'SP CALLBACK URL,
    issuer: 'SP URL',
    cert: fs.readFileSync('IDP CERTIFICATE IN .CER FORMAT', 'utf-8'),
    acceptedClockSkewMs: -5,
    identifierFormat: null,
    signatureAlgorithm: 'sha256',
    authnRequestBinding: 'HTTP-POST'
  },

And we are receiving this error on the netscaler IDP

"Parsing of presented Assertion failed; Please contact your administrator"

Netscaler is using "Signature Algorithm": RSA-SHA256, in the logs we can see a malformed message, so netscaler is not able to read the callback URL

I would be very thankful for any help of anyone that has managed to get this library working with Netscaler before

**Comment by markstos** [comment]
Sorry, no one is monitoring issues here to handle support requests. I recommend trying StackOverflow instead, using the `passport-saml` tag.
