### ISSUE TITLE
ADFS SamlRequest processing error, Relying party not configured with SAML Assertion Consumer Services

### ISSUE THREAD

**Issue by bjm88** [bergie/passport-saml#371]
Any ideas on this error below? On invoking the init to do the SamlRequest POST ADFS is giving an error:

> The relying party "https://example.com/saml/consume" is not configured with SAML Assertion Consumer Services
> Relying party: https://example.com/saml/consume
> 
> This request Failed.
> 
> User Action
> Use the AD FS Management snap-in to configure one or more Assertion Consumer Services for this relying party.

Any idea how to resolve this?   I was not sure with this library how to generate assertions/claims in the AuthRequest or setup and convey to IDP that we want to get a set of attributes back like email... ?

How to use this: "attributeConsumingServiceIndex" . ? (I just put it to "1" and it didn't help.

**Comment by ahavriluk** [comment]
You need to register your callback URL in ADFS. Open your Relaying Part Trust properties dialog and add your callback URL in Endpoints tab.

I wasn't using attributeConsumingServiceIndex, so I can't help you with that.
We setup our claims for a specific Relaying Party in ADFS. Each claim was generating an particular assertion in SAML response.
