### ISSUE TITLE
SP initiated SLO HTTP-Redirect not working

### ISSUE THREAD

**Issue by asleboon** [bergie/passport-saml#376]
Hi

I was recently handed the task to figure out why the application doesn't sign the user out from the IdP. I have followed the standard way of doing it which seems to be something like this.

```js
const strategy = new SamlStrategy(
  {
    callbackUrl: process.env.CALLBACK_URL,
    entryPoint: process.env.ENTRY_POINT,
    issuer: process.env.ISSUER,
    logoutUrl: process.env.LOGOUT_URL,
    logoutCallbackUrl: process.env.LOGOUT_CALLBACK_URL,
  },
  strategyCallback,
);

app.get('/api/logout', (req, res) => {
  const currentUser = getCurrentUser(req);
  const user = {
    nameID: currentUser.nameID,
    nameIDFormat: currentUser.nameIDFormat,
    sessionIndex: currentUser.sessionIndex,
  };
  req.user = user;
  strategy.logout(req, (err, requestURL) => {
      req.logout();
      res.redirect(requestURL);
  });

app.post('/api/logout/callback', (req, res) => {
  req.logout();
  res.redirect('/');
});
```

The problem is that the browser sends an OPTIONS request and we receive a 400 "bad request" error. I'm fairly new to passport-saml and I can't really figure out if something is wrong with the SAMLRequest. I'm redirecting the user to the correct endpoint and with the correct user attributes attached to the request. Can someone help me shed some light on this issue? 

Thank you

**Comment by markstos** [comment]
Sorry, there's no bandwidth to answer support requests here. You can try StackOverflow with the passport-saml tag.
