### ISSUE TITLE
Fall back to cert in saml options in MultiSamlStrategy generateServiceProviderMetadata

### ISSUE THREAD

**Issue by ssbrewster** [bergie/passport-saml#377]
`MultiSamlStrategy.prototype.generateServiceProviderMetadata` calls `getSamlOptions` that allows fetching saml configuration for each provider. This can include the `cert` and I *think* that it would be a common case for this cert to match the decryption and signing private keys. For my use case I fetch the saml config from a service so with the current code I'm forced to make two requests for the config. 

Could `generateServiceProviderMetadata` fall back to the options if the params are not provided something like the example below (I'm happy to submit a PR if this approach is ok)? 
```
MultiSamlStrategy.prototype.generateServiceProviderMetadata = function( req, decryptionCert, signingCert, callback ) {
  if (typeof callback !== 'function') {
    throw new Error("Metadata can't be provided synchronously for MultiSamlStrategy.");
  }

  var self = this;

  return this._options.getSamlOptions(req, function (err, samlOptions) {
    if (err) {
      return callback(err);
    }

    // mutating the params here could be avoided 
    decryptionCert = decryptionCert ? decryptionCert : samlOptions.cert;
    signingCert = signingCert ? signingCert : samlOptions.cert;

    self._saml = new saml.SAML(Object.assign({}, self._options, samlOptions));
    return callback(null, self.constructor.super_.prototype.generateServiceProviderMetadata.call(self, decryptionCert, signingCert ));
  });
};
```

**Comment by markstos** [comment]
The `cert` is the signing cert. `decryptionPvk` is used for decryption.

**Comment by ssbrewster** [comment]
The `decryptionCert` here refers to the public certificate that matches the private key.
```
The decryptionCert argument should be a public certificate matching the decryptionPvk and is required if the strategy is configured with a decryptionPvk.
```
My use case is a bit of an edge case so not worth a PR because it only really applies when testing s closing.
