### ISSUE TITLE
pass additionalParams in authenticate function

### ISSUE THREAD

**Issue by jacyuan** [bergie/passport-saml#382]
Hi,

(Version : 1.1.0)
projection with TypeScript

I'm trying to find a solution to pass / forward params to saml callback route.
I found this [issue](https://github.com/bergie/passport-saml/pull/136) which suggests to use the additionalParam, but passing "additionalParam" ends up with compilation error...

Each time when I try to ctrl+clic on the 'authenticate' function, it will point to the implementation under the "node_modules/@types/passport" folder, where the AuthenticateOptions interface does not have the "additionalParam" property.

Below are my test, something's wrong with it ?
Thank you for your advice.

```
import * as bodyParser from 'body-parser';
import * as express from 'express';
import * as passportSaml from 'passport-saml';
import * as passport from 'passport';
import * as fs from 'fs';
import * as https from 'https';
const SamlStrategy = require('passport-saml').Strategy;


passport.use(
  new SamlStrategy(
    {
      passReqToCallback: true,
....


app.get(
  '/login',
    passport.authenticate('saml', { failureRedirect: '/login', failureFlash: true, additionalParams:{RelayState:'test'} }),
  (req: any, res: any, next: any) => {
    //   passport.authenticate(
....

-----package.json
  "dependencies": {
    "express": "^4.17.1",
    "passport": "^0.4.0",
    "passport-saml": "^1.1.0",
  },
  "devDependencies": {
    "@types/express": "^4.16.1",
    "@types/passport-saml": "^1.1.0",
    "ts-node": "^8.0.3",
    "typescript": "~3.1.0"
  }
```

**Comment by codeocelot** [comment]
Although the docs don't mention it, the SAML spec allows for a RelayState field in the body so you can pass state and receive it in the callback.  Take a look at the following snippet. 

<img width="753" alt="Screen Shot 2019-07-23 at 8 24 12 PM" src="https://user-images.githubusercontent.com/4086894/61762859-3520a480-ad88-11e9-8dc9-9485e5fa1ea0.png">

**Comment by jacyuan** [comment]
Hi @codeocelot, 

I saw that we can pass params through relayState, but I didn't know that could be set in the requestHandler level before applying authenticate function.

That's a good idea I think, I'll test it.

Thanks a lot for your suggestion !
