### ISSUE TITLE
express - redirected url not submitting form gives SAML assertion not yet valid

### ISSUE THREAD

**Issue by pks90** [bergie/passport-saml#384]
I am not sure if it is something related to the browser update but the url to which I get redirected successfully by the **IDP** doesn't submit the post request i.e. I am expected to do it via browser. Can I do anything about it ? 

More details in the following SO thread,

https://stackoverflow.com/q/57290983/1503130

**Comment by markstos** [comment]
I see the issue was answered on SO. Closing here.
