### ISSUE TITLE
Add `InResponseTo` to the profile object

### ISSUE THREAD

**Issue by jasonbw** [bergie/passport-saml#393]
The code I'm working on needs the `InResponseTo` field. I see that it is getting parsed, but not  added to the profile object.

The ask: add `InResponseTo` to the profile object so that I can get it in `passport.use`.

**Comment by markstos** [comment]
Seems like a reasonable request. A PR is welcome, or you can submit a proposed pseudo-code solution for review. You can access it indirectly now:

```
user.getAssertion()['Assertion']
	['Subject'][0]
	['SubjectConfirmation'][0]
	['SubjectConfirmationData'][0]
	['$']['InResponseTo']
```

That's not particularly intuitive or readable.

**Comment by markstos** [comment]
Looks OK to me. I'll wait to see if others have feedback on the proposal. @sibelius @cjbarth @josecolella ?

**Comment by cjbarth** [comment]
Is there a possibility that there might be several inResponseTo values for the different Subjects and associated confirmations? I'm out of town now on a phone, otherwise I'd check myself.
