### ISSUE TITLE
Documentation error for 'host' parameter

### ISSUE THREAD

**Issue by kvanrobbroeck** [bergie/passport-saml#410]
Hello,

Documentation here: http://www.passportjs.org/packages/passport-saml/

States that for the `host` property:
> host for callback; will be combined with path and protocol to construct callback url if callbackUrl is not specified (default: localhost)`.

But in reality, it seems to default to the value of `Host` header (which, when developing locally, tends to be localhost(:port). (this is fine).

**Comment by kvanrobbroeck** [comment]
Created a PR with proposed fix: https://github.com/bergie/passport-saml/pull/411

**Comment by markstos** [comment]
I'm closing this, as related discussion can continue in the related PR #411.
