### ISSUE TITLE
Handling multiple configurations for SAML selected at runtime

### ISSUE THREAD

**Issue by chrisjleaf** [bergie/passport-saml#56]
I'm working with Okta as a provider for SAML authentication and this repo works wonderfully for one "company" because it only needs one set of configuration parameters. My site however can consume several different companies' logins which we divide by "groups" of logins, meaning it requires different `entryPoint`, `issuer` and `cert` options per group. Ideally I'd like to provide this as part of the call to `authenticate` because then it can work in real time. 

I made a temporary fix for my app, creating a `req.saml = { issuer: ..., cert: ..., entryPoint:... }` generated by another middleware which seems like the ideal way to pass it in. However I then override the options hash stored in the `_saml.options` which seems non-ideal because the chance to have a default is lost and opens up to a lot of bugs caused by unintentionally overriding defaults.

I was in a bit of hurry to get it so I haven't gone through the code extensively enough to make a proper pull request with a real solution. Does the above situation seem like something desirable? I can help implement it if needed (not sure when I'll start by myself though).

**Comment by markstos** [comment]
This may be worth re-visiting as the author of `passports` no longer users or maintains it. 

It seems to me to handle multiple configurations in `passport-saml`, the primary problem is that we hardcoded the `name` value and this value is set read-only. Beyond that, is there a problem with loading multiple strategies with different names using `passport-saml` ?

**Comment by markstos** [comment]
Here's the patch I'm testing out now to natively enable multiple SAML support:

https://github.com/RideAmigosCorp/passport-saml/commit/594eed35cc0765172d17487b3611eddffaadd2ea

Maybe @ploer @richjharris or @pdspicer are interested in authenticating against multiple SAML targets are interested to review the approach. ( I still need to real-world test the approach today. )

**Comment by markstos** [comment]
Official PR is here: https://github.com/bergie/passport-saml/pull/262/  With no dissenting comments here, I'm going to merge it.
