### ISSUE TITLE
Example with logout functionality

### ISSUE THREAD

**Issue by slawomir-pasko** [bergie/passport-saml#62]
As state in the title - I try to logout user using passport-saml. On the node.js side it works fine, but on the  side of Identity Provider I'm still logged in. Don't know how correctly pass and use logoffUrl to make sure, that session will be closed also on IP side.

thanx

**Comment by wambotron** [comment]
Check out pull request https://github.com/bergie/passport-saml/pull/72 for a fix for the current implementation. 

To actually get it to work on the IdP, you have to generate a logout request like
```javascript
var samlStrategy = passport._strategy('saml');

samlStrategy.logout(req, function(err, requestUrl) {
    // LOCAL logout
    req.logout();
    // redirect to the IdP with the encrypted SAML logout request
    res.redirect(requestUrl);
});
```

You'd also need to have a callback from the IdP set up so they can redirect back to your site (wherever you want to have them go). Alternatively, you can have a generic `exports.signout` function that only does local logout and redirects to the homepage, and use a custom `exports.samlSignout` function that takes care of **only** the `samlStrategy.logout` call.

I have this working in a local app based on my fork in the Pull Request above. Good luck!

**Comment by satblip** [comment]
Works perfectly on my side, thanks @wambotron !

**Comment by vijaykotha** [comment]
var SamlStrategy = require('passport-saml').Strategy;
router.get('/logout', function(req, res) {
	 
	 return SamlStrategy.logout(req, function(err, uri) {
		 return res.redirect(uri);
	 });
  });

Please could anyone help me as I am getting the error
TypeError: SamlStrategy.logout is not a function

**Comment by 1HzAkLAT** [comment]
i have one issue, i am using **cookieSession**  for passport-saml. i get the logout working but i have configured timeout, i get an error after timeout when user is trying to logout.

TypeError: Cannot read property 'nameIDFormat' of undefined.

TimeOut configuration:

`app.use(cookieSession({
	name: 'session',
	keys: ['keyHS'],
	maxAge: 10000 
}));
app.use(passport.initialize());
app.use(passport.session());`

 ```
samlStrategy.logout(req, function(){
                req.logout();
                res.redirect('/');
            });
```

What should i do here to redirect the user to login page after timeout.

**Comment by Amanuv19** [comment]
> var SamlStrategy = require('passport-saml').Strategy;
> router.get('/logout', function(req, res) {
> 
> ```
>  return SamlStrategy.logout(req, function(err, uri) {
> 	 return res.redirect(uri);
>  });
> ```
> 
> });
> 
> Please could anyone help me as I am getting the error
> TypeError: SamlStrategy.logout is not a function

FAcing the same error. Can anyone help
