### ISSUE TITLE
"Invalid RSAES-OAEP padding" Error

### ISSUE THREAD

**Issue by petermikitsh** [bergie/passport-saml#76]
Here's my SAML Configuration:

```javascript
var samlStrategy = new saml.Strategy({
    callbackUrl: 'https://myServer.rit.edu/login/callback',
    entryPoint: 'https://shibboleth.main.ad.rit.edu/idp/profile/SAML2/Redirect/SSO',
    issuer: 'https://myServer.rit.edu/shibboleth',
    identifierFormat: null,
    decryptionPvk: fs.readFileSync('/var/www/saml/key.pem', 'utf8'),
    cert: 'MIIDV......'
}, function(profile, done) {
    return done(null, profile);
});
```

Routes:

```javascript
app.get('/',
  passport.authenticate('saml', {failureRedirect: '/login/fail'}),
  function(req, res) {
    res.send('Authenticated');
  }
);

app.post('/login/callback',
   passport.authenticate('saml', { failureRedirect: '/login/fail' }),
  function(req, res) {
    res.redirect('/');
  }
);
````

General error catcher:

```javascript
app.use(function(err, req, res, next){
    console.log('Express error!');
    console.log("the error: " + JSON.stringify(err));
    next(err);
});
```
Shibboleth processes the request and a `SAMLResponse` is present in the header of callback route,  `/login/callback`.

An error is thrown at `passport.authenticate('saml', {failureRedirect: '/login/fail'})` in the `/` route. 
Console log:

```
Express error!
the error: {"message":"Invalid RSAES-OAEP padding."}
```

Any ideas?

**Comment by ploer** [comment]
Well, this is the error message you receive when the encrypted assertion does not match the private key you have supplied.  I.e., your shibboleth provider has a public key for you that does not match the decryptionPvk you are supplying.

Not sure if that is what you are seeing here, but the poor error message has bitten me several times in the past, I've been meaning to look into what we can do to give a better error here.  (it is being passed up from the underlying xmlenc library, not something generated direclty by passport-saml)

**Comment by petermikitsh** [comment]
I've confirmed with my identity provider that the correct public key is on file.

**Comment by ploer** [comment]
Then the next debugging step that comes to mind would be to step into the xmlenc `decrypt` call (or add some debug logging), and check if everything looks correct in there.  

It's definitely an error from the crypto layer, so if the right public key and private key are being used, I'd look at whether the private key is being loaded correctly, whether there is anything unusual about the format of those keys, etc.

**Comment by petermikitsh** [comment]
You are correct.

The XML module (xml-encryption) passes the encrypted data and private key to the 'forge' package:
https://github.com/auth0/node-xml-encryption/blob/master/lib/xmlenc.js#L208

Where the error is eventually thrown here:
https://github.com/digitalbazaar/forge/blob/master/js/pkcs1.js#L254 

I might try re-generating a new public/private key pair, and coordinating with the IdP. However, I don't know what else could be causing this, but it isn't your package.

**Comment by petermikitsh** [comment]
For anyone who comes across this, try regenerating your keys and certificate-- that was my issue. Also, try configuring with something like testshib.org (see #10) first before having to annoy your IdP Admin to reload your metadata frequently :)

**Comment by ploer** [comment]
I should put something about how useful testshib can be for debugging in the docs.  I'll file a bug for that.

**Comment by ricardosaracino** [comment]
Can someone point me in the direction of how to add aes256-cbc Assertion encryption support... i see this lib but not sure how to put it all together

https://github.com/auth0/node-xml-encryption
