### ISSUE TITLE
Getting 'Invalid Signature' error on SAML Response.  XML digests do not match

### ISSUE THREAD

**Issue by archa347** [bergie/passport-saml#82]
We're having some issues getting passport-saml setup with an Okta IDP.  We are getting a response back from our IDP, but the validation is failing.  Our IDP made sure that the signature and digests are done with SHA1.  Debugging into the code, (all the way into the XMLCrypto), I'm finding that it is failing when the digests don't match.  If we comment out the assertion validation, we are getting all the expected data so I'm pretty sure that SAML response is formatted properly.

I added in a console.log to get the canonXML that is being hashed for the digest, and the output is this:
```
<ns2:Assertion xmlns:ns2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_73bfe3a75de08316ce83cb05534a91aa2837" IssueInstant="2015-03-16T21:50:22Z" Version="2.0">&#xD;
        <ns2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">REDACTED</ns2:Issuer>&#xD;
        <ns2:Subject>&#xD;
            <ns2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">REDACTED</ns2:NameID>&#xD;
            <ns2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">&#xD;
                <ns2:SubjectConfirmationData NotOnOrAfter="2015-03-16T21:51:51Z" Recipient="https://REDACTED"></ns2:SubjectConfirmationData>&#xD;
            </ns2:SubjectConfirmation>&#xD;
        </ns2:Subject>&#xD;
        <ns2:Conditions NotBefore="2015-03-16T21:49:51Z" NotOnOrAfter="2015-03-16T21:51:51Z">&#xD;
            <ns2:AudienceRestriction>&#xD;
                <ns2:Audience>REDACTED</ns2:Audience>&#xD;
            </ns2:AudienceRestriction>&#xD;
        </ns2:Conditions>&#xD;
        <ns2:AuthnStatement AuthnInstant="2015-03-16T21:22:30Z" SessionIndex="rqRyLqemlvvu9A3OE9la6I1Z8iY=RgRbeg==" SessionNotOnOrAfter="2015-03-16T21:51:51Z">&#xD;
            <ns2:AuthnContext>&#xD;
                <ns2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</ns2:AuthnContextClassRef>&#xD;
            </ns2:AuthnContext>&#xD;
        </ns2:AuthnStatement>&#xD;
        <ns2:AttributeStatement>&#xD;
            <ns2:Attribute Name="FirstName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">&#xD;
                <ns2:AttributeValue>REDACTED</ns2:AttributeValue>&#xD;
            </ns2:Attribute>&#xD;
            <ns2:Attribute Name="LastName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">&#xD;
                <ns2:AttributeValue>REDACTED</ns2:AttributeValue>&#xD;
            </ns2:Attribute>&#xD;
        </ns2:AttributeStatement>&#xD;
    </ns2:Assertion>
```
One thing that concerns is me the '&#xD;' line endings, yet in the console we are also getting the line feeds and other whitespace.  I know next to nothing about XML canonicalization, but I'm wondering if the CRLFs in the SAML Response are not being properly transformed into the Canon XML for hashing.

Another thing we're wondering is if our configuration on the provider side has anything to do with digest and signature (aside from the cert).  For example, all the code examples we've seen have 'passport-saml' as the issuer, but we used our own issuer that we created basically at random and gave to our IDP.  We assumed that was just a placeholder for our own issuer.

Unfortunately, my team isn't in charge of the IDP so we don't really have much control over it, and we're also the first in our org to try to use Node.js with SAML, so we're treading new ground with our SAML team to get this working.

**Comment by ploer** [comment]
Interesting.  It certainly seems possible that there is a problem in the cannonicalization, but I would think that crlfs would be common enough that we'd have seen it if they caused problems.  I also use the library with Okta regularly myself and haven't had issues (I do find that you have to pay attention to compression settings with Okta, but that doesn't seem relevant here).

A couple of thoughts:

* What happens if you just strip out crlfs before feeding it through the verification?  (i.e., add a line in saml.js to replace all \r\n with \n in `xml` at the top of  `validatePostResponse`)
* Can you find some other tool that will validate XML signatures and feed the assertion xml through it to verify that it validates?

**Comment by archa347** [comment]
So I added a line in the validatePostResponse to remove CRs from the xml before the DOM parsing and it seems to work fine. Validations all pass.  After discovering that, I compared the value of the SAMLResponse before the base64 to UTF-8 conversion in `validatePostResponse` and the value of SAMLRespone after the Express bodyparser runs.

after body-parser SAMLResponse is    `PFJlc3BvbnNlIHhtbG5zPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIERl\r\nc3RpbmF0aW9uPSJodHRwczovL3NjZnRkZXYtd2ViMDhyMi5hbXIuY29ycC5pbnRlbC5jb20vbG9n\r\naW4vY2......`

This is the actual text, the `\r\n` are the literal characters.  This basically matches the raw text of the HTTP request, except with `\r\n` instead of `%0A%0D`.

Right before base64 to UTF-8 conversion in `validatePostResponse` the value of `container.SAMLResponse` is 
`PFJlc3BvbnNlIHhtbG5zPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIERl\r\r\nc3RpbmF0aW9uPSJodHRwczovL3NjZnRkZXYtd2ViMDhyMi5hbXIuY29ycC5pbnRlbC5jb20vbG9n\r\r\naW4vY2Fs.......`

In this the `\r`s and `\n`s refer to the CR and LF characters.  So somewhere in between the body parser and the `validatePostResponse` we are adding a CR character.  The only other middleware we have running is cookie-parser, method-override, and  express-session.  We are using Express 4.12.2 on Windows with Node 0.10.36

**Comment by archa347** [comment]
After some more playing around, I'm pretty sure that the issue is not the base64 string itself, but that there are CR characters in the encoded XML text.  So either the XML DOM parse is not correctly handling these characters, or the c14n canonicalization used by xml-crypto during the validation is not correctly handling the DOM.  

I drilled down all the way into validateReferences  method in the signed-xml module of xml-crypto and looked at the canon XML.  In the canon XML that is generated for validation, all the XML elements look like this 
`<ns2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">sepmp</ns2:Issuer>&#xD;`

Those `&#xD;` are on the end of each line with an element, in addition to normal line endings.

**Comment by ploer** [comment]
Sounds like you have made a lot of progress towards tracking this down.

If I read the above correctly, it sounds like either there is something wrong with your inputs to passport-saml, or else something going on in xml-crypto, maybe a cannonicalizaiton issue there.

I am definitely a bit confused though since you mentioned that this is coming from Okta and I know that Okta assertions are normally fine.  You showed an encoded SAML response that had some '\r\r\n' sequences in them... I think those should be harmless, but they definitely seem odd, and I wonder if whatever issue is introducing those might be somehow introducing the extra characters into the xml as well?

**Comment by archa347** [comment]
I was somewhat misinformed.  It seems that although we do have Okta in this environment, the IDP I'm actually communicating with is CA SiteMinder.  I found that stripping the CR characters from `xml` right after the base64 decoding in `validatePostResponse` allows the validation to finish successfully, otherwise the canonical XML ends up `&#xD;` on the end of each line.  I also took passport-saml out of the equation and implemented some of the same validation logic with xml-crypto in a small test module using the base64 SAMLResponse I captured, I had the same issues.  So at this point, I'm thinking its the canonicalization or the XML DOM parse.  I've opened up an issue with xml-crypto as well so hopefully we can get this resolved.

**Comment by ploer** [comment]
I'm going to close this issue since it sounds like there is no next step on passport-saml's side right now.

**Comment by markstos** [comment]
@archa347 How did your follow-up with `xml-crypto` go? That project doesn't keep a Changelog, so it's hard to tell if there have been an related fixes to `xml-crypto`. If so, it could be a good idea to version-bump the dependency that `passport-saml` requires.

**Comment by akash-goel** [comment]
I am working on test cases and getting Signature validation failed error on validating the SAML response . Please help me in identifying which parameters are responsible for Signature Creation and Validation

**Comment by markstos** [comment]
Start by checking out the passport SAML source code.
