### ISSUE TITLE
Different digest value's

### ISSUE THREAD

**Issue by Ruthenz** [bergie/passport-saml#86]
I'm trying to authenticate using ADFS and I just hit a problem which I don't really get and thought maybe I could get some help.
So after the the response from IdP comes back I can see it has CipherValue so I debugged and saw that the passport-saml decrypts it.
The problem is that while it decrypts it, it throws an exception at signed-xml.js row 291, when it tries to compare between the digest that it calculated and the digest that was recieved. 
Any idea why is this happening?

Thanks in advance!

**Comment by ploer** [comment]
Hmm, perhaps there is a cannonicalization issue?

You might take a look at issue #82 and see if your symptoms look similar.

To debug this, you might try looking around and see if you can find some other tool that will calculate a digest on your document, to compare that to the one that xml-crypto is generating...
