### ISSUE TITLE
Instantiating SamlStrategy causes object is not a function error

### ISSUE THREAD

**Issue by CamHenlin** [bergie/passport-saml#88]
Hi, I'm trying to use the SamlStrategy in an app and noticed that the app throws an error any time I try to instantiate the SamlStrategy regardless of input options. I made an extremely minimalist example app to show this behavior: https://github.com/CamHenlin/broken-passport-saml-example

**Comment by ploer** [comment]
You want your SamlStrategy variable to be configured as:

```  , SamlStrategy = require('passport-saml').Strategy;```

I'll update the doc page to be more explict about that.  If you are looking for examples that show usage, the self-tests are probably a helpful place to start and you could have seen this usage there.
