### ISSUE TITLE
HTTP POST Binding in passport-saml

### ISSUE THREAD

**Issue by whirp** [bergie/passport-saml#90]
Hi, 
I've to use  passport-saml in  HTTP POST Binding. Would you please help me to find a way to add this implementation to this module? Is there a pre-existent module doing this?

Thanks

**Comment by ploer** [comment]
You want to make requests to the IdP using POST bindings?  (responses to passport-saml are already supported via POST binding).

I'm not aware of any module that adds this functionality.  I'd be happy to consider a PR if you wanted to try to add a configuration option to support this.  (I haven't studied what this would take but you'd probably have to abstract out a bunch of hardwired assumptions in the current module).

**Comment by cheton** [comment]
Hi @ploer 

I created a pull request #129 to add HTTP-POST binding support for the SAML &lt;AuthnRequest&gt;.

Since It is necessary to use HTTP-POST binding for all requests to our IdP servers, may I know when will this PR be added to passport-saml?

Thanks
