### ISSUE TITLE
Adding HTTP headers

### ISSUE THREAD

**Issue by britztopher** [bergie/passport-saml#96]
Is there a way to add http headers to the request to the Authorization server?  For instance, I have a consumer key that needs to be included in the Authorization header.

**Comment by ploer** [comment]
The requests to the IDP (is that what you mean by authorization server?) happen via client redirection, so I'm not sure I see how that would work.

If your IDP requires this additional parameter, maybe it can be supplied through `additionalParams` or `additionalAuthorizeParams`?
