### ISSUE TITLE
Is there a preferred way to configure Passport-SAML to support dynamic IdPs?

### ISSUE THREAD

**Issue by alexanderbanks** [bergie/passport-saml#99]
So I'm working on an app that needs to support dynamic IdPs. Upon receiving a request, the database is queried for a config JSON object based on some request parameters. That config object will contain any and all data about the IdP we're trying to work with for SSO. How would I go about configuring passport-saml to run with dynamic configurations? Is there a smarter approach?

**Comment by ploer** [comment]
Would https://www.npmjs.com/package/passports get you what you want?
